In [190]:
import polars as pl
import torch
from sklearn.metrics import classification_report
from sklearn.neighbors import NearestNeighbors
from sklearn.linear_model import Lasso
import numpy as np
from amaretto_mlp import *
from utils_b import *
from autoencoder import *
from explanation import *

%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# 1. Data & model preperatiom

In [2]:
pl.Config.set_tbl_cols(150)

polars.config.Config

In [3]:
df = pl.read_parquet("amaretto_transformed_scaled.pq")
df_train, df_val, df_test = split_data(df)

#columns_to_drop = ['id', 'Anomaly', 'Anomaly_bin', 'Originator', 'datetime']
columns_to_drop = ['id', 'Anomaly', 'Anomaly_bin', 'Originator', 'datetime', 'day_of_week', 'day_of_month', 'hour', 'minute']

target_column = 'Anomaly'
y_train = df_train.select(target_column).to_numpy().flatten()
df_train = df_train.drop(columns_to_drop)
X_train = df_train.to_numpy()
y_val = df_val.select(target_column).to_numpy().flatten()
X_val = df_val.drop(columns_to_drop).to_numpy()
y_test = df_test.select(target_column).to_numpy().flatten()
X_test = df_test.drop(columns_to_drop).to_numpy()

train_dataset = AmarettoDataset(X_train, y_train)
val_dataset = AmarettoDataset(X_val, y_val)
test_dataset = AmarettoDataset(X_test, y_test)
feature_names = df_train.columns
print(X_train.shape)
print(X_test.shape)

(24451934, 121)
(2765755, 121)

In [4]:
train_loader = DataLoader(train_dataset, batch_size=256, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=256, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=256, num_workers=2)
input_dim = X_train.shape[1]
df_train, df_val, df_test = split_data(df)
print(len(train_loader))

95516

In [5]:
model = CombinedModel(input_dim=X_train.shape[1], hidden_layers=[64, 64], latent_dim=16, num_classes=6)
model.load_state_dict(torch.load("model_combined_2.pth"))
print(model)

CombinedModel(
  (encoder): Encoder(
    (network): Sequential(
      (0): Linear(in_features=121, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
      (4): Linear(in_features=64, out_features=16, bias=True)
    )
  )
  (decoder): Decoder(
    (network): Sequential(
      (0): Linear(in_features=16, out_features=64, bias=True)
      (1): Tanh()
      (2): Linear(in_features=64, out_features=64, bias=True)
      (3): Tanh()
      (4): Linear(in_features=64, out_features=121, bias=True)
    )
  )
  (classifier): Classifier(
    (network): Sequential(
      (0): Linear(in_features=16, out_features=16, bias=True)
      (1): ReLU()
      (2): Linear(in_features=16, out_features=6, bias=True)
    )
  )
)

In [6]:
model.eval()
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
with torch.no_grad():
    _, y_pred_train, z_train = model(X_train_tensor)
    y_pred_train = torch.argmax(y_pred_train, dim=1)
y_pred_train = y_pred_train.cpu().detach().numpy()
print(y_pred_train.shape)
z_train = z_train.cpu().numpy()
print(z_train.shape)

(24451934,)
(24451934, 16)

In [7]:
model.eval()
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
with torch.no_grad():
    _, y_pred_test, z_test = model(X_test_tensor)
    y_pred_test = torch.argmax(y_pred_test, dim=1)
y_pred_test = y_pred_test.cpu().detach().numpy()
print(y_pred_test.shape)
z_test = z_test.cpu().numpy()
print(z_test.shape)

(2765755,)
(2765755, 16)

In [8]:
df_test = df_test.with_columns(pl.Series("Model Prediction", y_pred_test))
df_test = df_test.select(["Model Prediction", *df_test.columns[:-1]])  
df_test = df_test.with_row_index(name="index")
df_test

shape: (2_765_755, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 270 ┆ 201 ┆ Cli ┆ 0   ┆ 0   ┆ 0.5 ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 1   ┆ 18  ┆ 0   ┆ 0   ┆ fal ┆ 1.7 ┆ 1.2 ┆ 1.0 ┆ 0.9 ┆ -2. ┆ 1.6 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -1. ┆ -0. ┆ 0.0 ┆ 0.7 ┆ 1.3 ┆ 0.5 ┆ -1. ┆ 0.2 ┆ 3.6 ┆ 0.1 ┆ 1.4 ┆ -28 ┆ -59 ┆ -70 ┆ -0. ┆ -40 ┆ -33 ┆ -40 ┆ 0.2 ┆ -36 ┆ -60 ┆ -64 ┆ -0. ┆ -17 ┆ -20 ┆ -22 ┆ -0. ┆ -84 ┆ -85 ┆ -91 ┆ -0. ┆ -17 ┆ -15 ┆ -19 ┆ 0.2 ┆ -12 ┆ -33 ┆ -42 ┆ 0.3 ┆ -9. ┆ -28 ┆ -34 ┆ 0.1 ┆ -9. ┆ -28 ┆ -35 ┆ 0.2 ┆ -12 ┆ -30 ┆ -31 ┆ -1. ┆ -9. ┆ -12 ┆ -14 ┆ 0.9 ┆ -3. ┆ -4. ┆ -5. ┆ 0.9 ┆ 1.3 ┆ 0.5 ┆ 1.6 ┆ 1.3 ┆ 1.4 ┆ 0.8 ┆ -1. ┆ 1.4 ┆ 0.5 ┆ 0.6 │
│     ┆     ┆ 250 ┆ 9-0 ┆ ent ┆     ┆     ┆ 077 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 712 ┆ 522 ┆ 397 ┆ 455 ┆ 511 ┆ 606 ┆ 284 ┆ 112 ┆     ┆     ┆ 390 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 433 ┆ 183 ┆ 071 ┆     ┆     ┆ 175 ┆ 290 ┆ 000 ┆ 000 ┆ 170 ┆ 654 ┆ 134 ┆ 287 ┆ 791 ┆ 205 ┆ 478 ┆ 062 ┆ 4.4 ┆ 4.7 ┆ 1.7 ┆ 891 ┆ .75 ┆ .50 ┆ .21 ┆ 057 ┆ 1.9 ┆ 3.5 ┆ 4.2 ┆ 499 ┆ 9.2 ┆ 9.1 ┆ 3.6 ┆ 014 ┆ .00 ┆ .95 ┆ .23 ┆ 372 ┆ .50 ┆ .68 ┆ .40 ┆ 214 ┆ .37 ┆ .28 ┆ .03 ┆ 261 ┆ 297 ┆ .43 ┆ .88 ┆ 037 ┆ 914 ┆ .65 ┆ .35 ┆ 786 ┆ .23 ┆ .77 ┆ .90 ┆ 070 ┆ 099 ┆ .93 ┆ .25 ┆ 553 ┆ 488 ┆ 521 ┆ 222 ┆ 394 ┆ 116 ┆ 011 ┆ 730 ┆ 915 ┆ 079 ┆ 277 ┆ 715 ┆ 314 ┆ 923 ┆ 243 │
│     ┆     ┆ 95  ┆ 3-1 ┆ _02 ┆     ┆     ┆ 11  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 47  ┆ 11  ┆ 28  ┆ 8   ┆ 988 ┆ 03  ┆ 955 ┆ 912 ┆     ┆     ┆ 533 ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 523 ┆ 119 ┆ 133 ┆     ┆     ┆ 981 ┆ 214 ┆ 167 ┆ 56  ┆ 8   ┆ 56  ┆ 69  ┆ 407 ┆ 49  ┆ 74  ┆ 73  ┆ 3   ┆ 187 ┆ 407 ┆ 758 ┆ 973 ┆ 188 ┆ 451 ┆ 207 ┆ 57  ┆ 102 ┆ 062 ┆ 483 ┆ 873 ┆ 266 ┆ 522 ┆ 747 ┆ 74  ┆ 280 ┆ 190 ┆ 738 ┆ 707 ┆ 082 ┆ 104 ┆ 706 ┆ 78  ┆ 598 ┆ 558 ┆ 697 ┆ 99  ┆ 571 ┆ 827 ┆ 839 ┆ 04  ┆ 659 ┆ 632 ┆ 344 ┆ 17  ┆ 403 ┆ 261 ┆ 101 ┆ 623 ┆ 869 ┆ 878 ┆ 722 ┆ 28  ┆ 935 ┆ 771 ┆ 825 ┆ 8   ┆ 93  ┆ 52  ┆ 7   ┆ 98  ┆ 14  ┆ 23  ┆ 182 ┆ 43  ┆ 85  ┆ 24  │
│     ┆     ┆     ┆ 8   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 07  ┆ 25  ┆ 93  ┆     ┆ 6   ┆ 3   ┆ 6   ┆     ┆ 59  ┆ 78  ┆ 09  ┆     ┆ 01  ┆ 84  ┆ 53  ┆     ┆ 3   ┆ 5   ┆ 3   ┆     ┆ 1   ┆ 7   ┆ 2   ┆     ┆ 5   ┆ 1   ┆ 5   ┆     ┆     ┆ 1   ┆ 9   ┆     ┆     ┆ 6   ┆ 6   ┆     ┆ 5   ┆ 1   ┆     ┆     ┆     ┆ 8   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 01  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 2   ┆ 270 ┆ 201 ┆ Cli ┆ 0   ┆ 0   ┆ 0.6 ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 1   ┆ 18  ┆ 0   ┆ 0   ┆ fal ┆ 1.7 ┆ 1.2 ┆ 1.0 ┆ 0.9 ┆ 0.8 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.7 ┆ 1.3 ┆ 0.5 ┆ -1. ┆ 0.2 ┆ 3.6 ┆ 0.1 ┆ 1.4 ┆ -37 ┆ -78 ┆ -92 ┆ -0. ┆ -21 ┆ -18 ┆ -22 ┆ 0.2 ┆ -36 ┆ -60 ┆ -64 ┆ -0. ┆ -64 ┆ -76 ┆ -81 ┆ -0. ┆ 82. ┆ 86. ┆ 93. ┆ -0. ┆ -16 ┆ -15 ┆ -18 ┆ 0.2 ┆ -12 ┆ -33 ┆ -42 ┆ 1.4 ┆ -9. ┆ -28 ┆ -34 ┆ 0.9 ┆ -9. ┆ -28 ┆ -35 ┆ -0. ┆ -12 ┆ -30 ┆ -31 ┆ -0. ┆ -9. ┆ -12 ┆ -14 ┆ -0. ┆ -3. ┆ -4. ┆ -5. ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.5 ┆ 0.3 ┆ 0.2 ┆ 0.7 ┆ -1. ┆ 1.4 ┆ 0.5 ┆ 0.6 │
│     ┆     ┆ 564 ┆ 9-0 ┆ ent ┆     ┆     ┆ 041 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 867 ┆ 551 ┆ 425 ┆ 400 ┆ 868 ┆ 669 ┆ 284 ┆ 112 ┆     ┆     ┆ 390 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 433 ┆ 183 ┆ 071 ┆     ┆     ┆ 252 ┆ 000 ┆ 000 ┆ 000 ┆ 170 ┆ 654 ┆ 134 ┆ 287 ┆ 791 ┆ 205 ┆ 478 ┆ 062 ┆ .47 ┆ .35 ┆ .47 ┆ 892 ┆ .35 ┆ .74 ┆ .97 ┆ 057 ┆ 1.9 ┆ 3.5 ┆ 4.2 ┆ 499 ┆ .46 ┆ .06 ┆ .66 ┆ 014 ┆ 204 ┆ 739 ┆ 111 ┆ 372 ┆ .76 ┆ .12 ┆ .76 ┆ 214 ┆ .37 ┆ .28 ┆ .03 ┆ 054 ┆ 297 ┆ .43 ┆ .88 ┆ 941 ┆ 914 ┆ .65 ┆ .35 ┆ 169 ┆ .23 ┆ .77 ┆ .90 ┆ 497 ┆ 099 ┆ .93 ┆ .25 ┆ 458 ┆ 488 ┆ 521 ┆ 222 ┆ 583 ┆ 813 ┆ 629 ┆ 749 ┆ 322 ┆ 252 ┆ 805 ┆ 701 ┆ 222 ┆ 854 ┆ 330 │
│     ┆     ┆ 75  ┆ 3-1 ┆ _26 ┆     ┆     ┆ 78  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42  ┆ 48  ┆ 93  ┆ 21  ┆ 29  ┆ 069 ┆ 955 ┆ 912 ┆     ┆     ┆ 533 ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 523 ┆ 119 ┆ 133 ┆     ┆     ┆ 35  ┆ 208 ┆ 167 ┆ 56  ┆ 8   ┆ 56  ┆ 69  ┆ 407 ┆ 49  ┆ 74  ┆ 73  ┆ 3   ┆ 967 ┆ 520 ┆ 627 ┆ 021 ┆ 289 ┆ 994 ┆ 308 ┆ 57  ┆ 102 ┆ 062 ┆ 483 ┆ 896 ┆ 955 ┆ 880 ┆ 324 ┆ 74  ┆ 164 ┆ 843 ┆ 237 ┆ 707 ┆ 725 ┆ 966 ┆ 240 ┆ 79  ┆ 598 ┆ 558 ┆ 697 ┆ 94  ┆ 571 ┆ 827 ┆ 839 ┆ 96  ┆ 659 ┆ 632 ┆ 344 ┆ 833 ┆ 403 ┆ 261 ┆ 101 ┆ 217 ┆ 869 ┆ 878 ┆ 722 ┆ 814 ┆ 935 ┆ 771 ┆ 825 ┆ 68  ┆ 53  ┆ 977 ┆ 98  ┆ 08  ┆ 68  ┆ 38  ┆ 164 ┆ 96  ┆ 77  ┆ 51  │

In [9]:
df_train = df_train.with_columns(pl.Series("Model Prediction", y_pred_train))
df_train = df_train.select(["Model Prediction", *df_train.columns[:-1]])  
df_train = df_train.with_row_index(name="index")
df_train

shape: (24_451_934, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 151 ┆ 201 ┆ Cli ┆ 0   ┆ 0   ┆ 0.3 ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 2   ┆ 1   ┆ 0   ┆ 0   ┆ fal ┆ -5. ┆ -4. ┆ -3. ┆ -2. ┆ -2. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.8 ┆ 0.0 ┆ 1.4 ┆ 0.2 ┆ 3.6 ┆ 0.1 ┆ 1.4 ┆ -28 ┆ -59 ┆ -70 ┆ -18 ┆ -40 ┆ -33 ┆ -40 ┆ -67 ┆ -36 ┆ -60 ┆ -64 ┆ -16 ┆ -17 ┆ -20 ┆ -22 ┆ -27 ┆ -84 ┆ -85 ┆ -91 ┆ -11 ┆ -17 ┆ -15 ┆ -19 ┆ -34 ┆ -12 ┆ -33 ┆ -42 ┆ -12 ┆ -9. ┆ -28 ┆ -34 ┆ -11 ┆ -9. ┆ -28 ┆ -35 ┆ -93 ┆ -12 ┆ -30 ┆ -31 ┆ -55 ┆ -9. ┆ -12 ┆ -14 ┆ -17 ┆ -3. ┆ -4. ┆ -5. ┆ -7. ┆ -6. ┆ -5. ┆ -4. ┆ -5. ┆ -6. ┆ 19. ┆ 3.2 ┆ 10. ┆ 1.3 ┆ 1.7 │
│     ┆     ┆ 925 ┆ 9-0 ┆ ent ┆     ┆     ┆ 926 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 176 ┆ 005 ┆ 292 ┆ 835 ┆ 511 ┆ 669 ┆ 284 ┆ 112 ┆     ┆     ┆ 390 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 433 ┆ 183 ┆ 071 ┆     ┆     ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 811 ┆ 796 ┆ 876 ┆ 763 ┆ 791 ┆ 205 ┆ 478 ┆ 062 ┆ 4.4 ┆ 4.7 ┆ 1.7 ┆ 50. ┆ .75 ┆ .50 ┆ .21 ┆ .35 ┆ 1.9 ┆ 3.5 ┆ 4.2 ┆ 19. ┆ 9.2 ┆ 9.1 ┆ 3.6 ┆ 9.7 ┆ .00 ┆ .95 ┆ .23 ┆ 7.6 ┆ .50 ┆ .68 ┆ .40 ┆ .61 ┆ .37 ┆ .28 ┆ .03 ┆ 2.0 ┆ 297 ┆ .43 ┆ .88 ┆ 6.0 ┆ 914 ┆ .65 ┆ .35 ┆ .63 ┆ .23 ┆ .77 ┆ .90 ┆ .86 ┆ 099 ┆ .93 ┆ .25 ┆ .68 ┆ 488 ┆ 521 ┆ 222 ┆ 016 ┆ 186 ┆ 461 ┆ 457 ┆ 261 ┆ 025 ┆ 130 ┆ 734 ┆ 168 ┆ 127 ┆ 592 │
│     ┆     ┆     ┆ 1-0 ┆ _25 ┆     ┆     ┆ 79  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 871 ┆ 506 ┆ 225 ┆ 853 ┆ 988 ┆ 069 ┆ 955 ┆ 912 ┆     ┆     ┆ 533 ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 523 ┆ 119 ┆ 133 ┆     ┆     ┆ 079 ┆ 208 ┆ 167 ┆ 56  ┆ 648 ┆ 12  ┆ 94  ┆ 85  ┆ 49  ┆ 74  ┆ 73  ┆ 3   ┆ 187 ┆ 407 ┆ 758 ┆ 737 ┆ 188 ┆ 451 ┆ 207 ┆ 270 ┆ 102 ┆ 062 ┆ 483 ┆ 504 ┆ 266 ┆ 522 ┆ 747 ┆ 948 ┆ 280 ┆ 190 ┆ 738 ┆ 032 ┆ 082 ┆ 104 ┆ 706 ┆ 571 ┆ 598 ┆ 558 ┆ 697 ┆ 083 ┆ 571 ┆ 827 ┆ 839 ┆ 543 ┆ 659 ┆ 632 ┆ 344 ┆ 516 ┆ 403 ┆ 261 ┆ 101 ┆ 845 ┆ 869 ┆ 878 ┆ 722 ┆ 486 ┆ 935 ┆ 771 ┆ 825 ┆ 616 ┆ 89  ┆ 002 ┆ 34  ┆ 721 ┆ 219 ┆ 933 ┆ 89  ┆ 608 ┆ 85  ┆ 53  │
│     ┆     ┆     ┆ 1   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 07  ┆ 25  ┆ 93  ┆ 809 ┆ 6   ┆ 3   ┆ 6   ┆ 5   ┆ 59  ┆ 78  ┆ 09  ┆ 634 ┆ 01  ┆ 84  ┆ 53  ┆ 52  ┆ 3   ┆ 5   ┆ 3   ┆ 53  ┆ 1   ┆ 7   ┆ 2   ┆ 4   ┆ 5   ┆ 1   ┆ 5   ┆ 72  ┆     ┆ 1   ┆ 9   ┆ 96  ┆     ┆ 6   ┆ 6   ┆ 3   ┆ 5   ┆ 1   ┆     ┆     ┆     ┆ 8   ┆ 3   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 3   ┆ 196 ┆ 201 ┆ Cli ┆ 0   ┆ 0   ┆ 0.5 ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 2   ┆ 1   ┆ 0   ┆ 0   ┆ fal ┆ -5. ┆ -4. ┆ -3. ┆ -2. ┆ -2. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.8 ┆ 0.0 ┆ 1.4 ┆ 0.2 ┆ 3.6 ┆ 0.1 ┆ 1.4 ┆ -43 ┆ -90 ┆ -10 ┆ -28 ┆ -21 ┆ -19 ┆ -23 ┆ -40 ┆ -36 ┆ -60 ┆ -64 ┆ -16 ┆ -67 ┆ -79 ┆ -84 ┆ -10 ┆ 78. ┆ 82. ┆ 88. ┆ 117 ┆ -16 ┆ -14 ┆ -18 ┆ -32 ┆ -12 ┆ -33 ┆ -42 ┆ -12 ┆ -9. ┆ -28 ┆ -34 ┆ -11 ┆ -9. ┆ -28 ┆ -35 ┆ -93 ┆ -12 ┆ -30 ┆ -31 ┆ -55 ┆ -9. ┆ -12 ┆ -14 ┆ -17 ┆ -3. ┆ -4. ┆ -5. ┆ -7. ┆ -6. ┆ -5. ┆ -4. ┆ -5. ┆ -6. ┆ 19. ┆ 3.2 ┆ 10. ┆ 1.3 ┆ 1.7 │
│     ┆     ┆ 838 ┆ 9-0 ┆ ent ┆     ┆     ┆ 412 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 176 ┆ 005 ┆ 292 ┆ 835 ┆ 511 ┆ 669 ┆ 284 ┆ 112 ┆     ┆     ┆ 390 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 433 ┆ 183 ┆ 071 ┆     ┆     ┆ 000 ┆ 000 ┆ 000 ┆ 000 ┆ 811 ┆ 796 ┆ 876 ┆ 763 ┆ 791 ┆ 205 ┆ 478 ┆ 062 ┆ .18 ┆ .28 ┆ 6.5 ┆ 1.1 ┆ .80 ┆ .09 ┆ .37 ┆ .94 ┆ 1.9 ┆ 3.5 ┆ 4.2 ┆ 19. ┆ .12 ┆ .14 ┆ .94 ┆ 7.1 ┆ 364 ┆ 750 ┆ 852 ┆ .64 ┆ .24 ┆ .73 ┆ .30 ┆ .89 ┆ .37 ┆ .28 ┆ .03 ┆ 2.0 ┆ 297 ┆ .43 ┆ .88 ┆ 6.0 ┆ 914 ┆ .65 ┆ .35 ┆ .63 ┆ .23 ┆ .77 ┆ .90 ┆ .86 ┆ 099 ┆ .93 ┆ .25 ┆ .68 ┆ 488 ┆ 521 ┆ 222 ┆ 016 ┆ 186 ┆ 461 ┆ 457 ┆ 261 ┆ 025 ┆ 130 ┆ 734 ┆ 168 ┆ 127 ┆ 592 │
│     ┆     ┆     ┆ 1-0 ┆ _13 ┆     ┆     ┆ 57  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 871 ┆ 506 ┆ 225 ┆ 853 ┆ 988 ┆ 069 ┆ 955 ┆ 912 ┆     ┆     ┆ 533 ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 523 ┆ 119 ┆ 133 ┆     ┆     ┆ 079 ┆ 208 ┆ 167 ┆ 56  ┆ 648 ┆ 12  ┆ 94  ┆ 85  ┆ 49  ┆ 74  ┆ 73  ┆ 3   ┆ 451 ┆ 486 ┆ 524 ┆ 432 ┆ 105 ┆ 080 ┆ 134 ┆ 737 ┆ 102 ┆ 062 ┆ 483 ┆ 504 ┆ 07  ┆ 332 ┆ 403 ┆ 859 ┆ 41  ┆ 277 ┆ 371 ┆ 226 ┆ 677 ┆ 846 ┆ 501 ┆ 498 ┆ 598 ┆ 558 ┆ 697 ┆ 083 ┆ 571 ┆ 827 ┆ 839 ┆ 543 ┆ 659 ┆ 632 ┆ 344 ┆ 516 ┆ 403 ┆ 261 ┆ 101 ┆ 845 ┆ 869 ┆ 878 ┆ 722 ┆ 486 ┆ 935 ┆ 771 ┆ 825 ┆ 616 ┆ 89  ┆ 002 ┆ 34  ┆ 721 ┆ 219 ┆ 933 ┆ 89  ┆ 608 ┆ 85  ┆ 53  │

In [10]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00   2759074
           1       0.35      0.84      0.49       576
           2       0.43      0.85      0.57       257
           3       0.70      0.95      0.81      1175
           4       0.41      0.83      0.55      2228
           5       0.52      0.43      0.47      2445

    accuracy                           1.00   2765755
   macro avg       0.57      0.82      0.65   2765755
weighted avg       1.00      1.00      1.00   2765755

In [11]:
mask_correct_preds = (y_test[y_test != 0] == y_pred_test[y_test != 0])
mask_wrong_preds = (y_test[y_test != 0] != y_pred_test[y_test != 0])
print(mask_correct_preds.sum())
print(mask_wrong_preds.sum())

4723
1958

In [12]:
df_correct_preds = df_test.filter((pl.col("Anomaly") != 0))
df_correct_preds = df_correct_preds.filter(mask_correct_preds)
df_wrong_preds = df_test.filter((pl.col("Anomaly") != 0))
df_wrong_preds = df_wrong_preds.filter(mask_wrong_preds)
print(df_correct_preds.height)
print(df_wrong_preds.height)

4723
1958

# 2. Explanations on input space

In [22]:
#X_train_n = X_train[y_pred_train == 0]
y_train_n = y_pred_train[y_pred_train == 0]
print(X_train_n.shape)
print(y_train_n.shape)

(24291851, 121)
(24291851,)

## 2.1. Small but highly frequent transactions generated within a short timeframe:
A pattern that contains multiple transactions below applicable reporting thresholds.

In [24]:
anomaly_type = 1
idx = 8357	
k = 9

In [25]:
X_train_a = X_train[y_pred_train == anomaly_type]
y_train_a = y_pred_train[y_pred_train == anomaly_type]
print(X_train_a.shape)
print(y_train_a.shape)

(16437, 121)
(16437,)

In [21]:
# z_train_n = z_train[y_train == 0]
# y_train_n = y_pred_train[y_pred_train == 0]
# z_train_a = z_train[y_pred_train == anomaly_type]
# y_train_a = y_pred_train[y_pred_train == anomaly_type]

In [26]:
# x = torch.tensor(X_test[idx], dtype=torch.float32).reshape(1, -1)
x = X_test[idx].reshape(1, -1)

print(x.shape)
print(x[:, :6])
print(y_test[idx])
print(y_pred_test[idx])

# model.encoder.eval()
# test_transaction_latent = model.encoder(x)
# test_transaction_latent = test_transaction_latent.cpu().detach().numpy()
# test_transaction_latent = test_transaction_latent.reshape(1, -1)
# test_transaction_latent.shape

(1, 121)
[[-1.37499299  1.          0.          1.          0.          0.        ]]
1
1

In [39]:
df_correct_preds.filter(pl.col("index") == idx)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 835 ┆ 1   ┆ 271 ┆ 201 ┆ Cli ┆ 1   ┆ 1   ┆ -1. ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 18  ┆ 7   ┆ 7   ┆ tru ┆ 2.0 ┆ 1.4 ┆ 1.1 ┆ 1.0 ┆ 1.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 2.4 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -2. ┆ 0.7 ┆ 1.3 ┆ 0.5 ┆ -1. ┆ -1. ┆ 1.2 ┆ -0. ┆ 1.1 ┆ -1. ┆ -3. ┆ -4. ┆ -0. ┆ -3. ┆ -4. ┆ -6. ┆ 0.2 ┆ -1. ┆ -1. ┆ -2. ┆ -0. ┆ -0. ┆ -2. ┆ -2. ┆ -0. ┆ 2.1 ┆ 0.7 ┆ 1.2 ┆ -0. ┆ -3. ┆ -4. ┆ -6. ┆ 0.2 ┆ -2. ┆ -5. ┆ -6. ┆ -0. ┆ -2. ┆ -8. ┆ -10 ┆ -0. ┆ -3. ┆ -9. ┆ -11 ┆ -0. ┆ 0.2 ┆ 1.4 ┆ 1.7 ┆ 0.9 ┆ -3. ┆ -3. ┆ -4. ┆ -0. ┆ -2. ┆ -2. ┆ -3. ┆ -0. ┆ -0. ┆ 0.1 ┆ 0.3 ┆ -0. ┆ 0.0 ┆ -2. ┆ 0.8 ┆ 1.4 ┆ -0. ┆ 0.6 │
│ 7   ┆     ┆ 812 ┆ 9-0 ┆ ent ┆     ┆     ┆ 374 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ 404 ┆ 458 ┆ 993 ┆ 770 ┆ 103 ┆ 669 ┆ 284 ┆ 112 ┆     ┆     ┆ 390 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 109 ┆ 183 ┆ 071 ┆     ┆     ┆ 058 ┆ 000 ┆ 000 ┆ 606 ┆ 170 ┆ 654 ┆ 134 ┆ 287 ┆ 409 ┆ 709 ┆ 831 ┆ 438 ┆ 830 ┆ 554 ┆ 216 ┆ 910 ┆ 529 ┆ 415 ┆ 225 ┆ 051 ┆ 218 ┆ 937 ┆ 099 ┆ 511 ┆ 676 ┆ 087 ┆ 719 ┆ 014 ┆ 986 ┆ 302 ┆ 958 ┆ 372 ┆ 446 ┆ 342 ┆ 150 ┆ 211 ┆ 867 ┆ 487 ┆ 993 ┆ 611 ┆ 789 ┆ 319 ┆ .27 ┆ 527 ┆ 272 ┆ 434 ┆ .81 ┆ 993 ┆ 315 ┆ 071 ┆ 191 ┆ 272 ┆ 093 ┆ 848 ┆ 589 ┆ 970 ┆ 270 ┆ 661 ┆ 286 ┆ 930 ┆ 260 ┆ 273 ┆ 834 ┆ 206 ┆ 002 ┆ 807 ┆ 727 ┆ 989 ┆ 519 ┆ 272 │
│     ┆     ┆ 76  ┆ 3-1 ┆ _12 ┆     ┆     ┆ 993 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 87  ┆ 17  ┆ 85  ┆ 04  ┆ 05  ┆ 069 ┆ 955 ┆ 912 ┆     ┆     ┆ 533 ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 51  ┆ 119 ┆ 133 ┆     ┆     ┆ 838 ┆ 208 ┆ 167 ┆ 994 ┆ 8   ┆ 56  ┆ 69  ┆ 407 ┆ 974 ┆ 89  ┆ 225 ┆ 92  ┆ 154 ┆ 36  ┆ 388 ┆ 444 ┆ 966 ┆ 957 ┆ 498 ┆ 58  ┆ 832 ┆ 383 ┆ 412 ┆ 044 ┆ 309 ┆ 921 ┆ 293 ┆ 74  ┆ 5   ┆ 3   ┆ 85  ┆ 707 ┆ 338 ┆ 24  ┆ 071 ┆ 89  ┆ 951 ┆ 623 ┆ 079 ┆ 904 ┆ 759 ┆ 886 ┆ 966 ┆ 784 ┆ 966 ┆ 822 ┆ 076 ┆ 851 ┆ 34  ┆ 06  ┆ 64  ┆ 01  ┆ 492 ┆ 477 ┆ 277 ┆ 284 ┆ 328 ┆ 877 ┆ 839 ┆ 763 ┆ 29  ┆ 59  ┆ 33  ┆ 731 ┆ 68  ┆ 199 ┆ 58  ┆ 69  ┆ 094 ┆ 25  │
│     ┆     ┆     ┆ 8   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 07: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 07: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 36  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [28]:
knn_normal = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_normal.fit(X_train_n)
distances_n, indices_n = knn_normal.kneighbors(x, n_neighbors=k)
print(indices_n)
print(distances_n)

knn_anomaly = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_anomaly.fit(X_train_a)
distances_a, indices_a = knn_anomaly.kneighbors(x, n_neighbors=k)
print(indices_a)
print(distances_a)

[[14130659 14132990 14132071 14132828 14134052 14133950 14133800  4559815
  14129022]]
[[6.27184505 6.44992011 6.56645748 6.75125626 6.76472677 6.83805775
  6.84874294 6.86661913 6.94610959]]
[[ 5498 10564 10565 10557  8497  8498 14241 14249  9687]]
[[7.39361877 7.57207238 7.71109299 8.01715007 8.21487136 8.51072918
  8.55808045 8.56119751 8.57957322]]

In [25]:
#df_train.filter(pl.col('Anomaly') == 0)[indices_n.flatten().tolist()]

In [26]:
#df_train.filter(pl.col('Anomaly') == 1)[indices_a.flatten().tolist()]

In [29]:
lasso_x_train = np.vstack((X_train_n[indices_n.flatten().tolist()], X_train_a[indices_a.flatten().tolist()]))
lasso_y_train = np.concatenate((y_train_n[indices_n.flatten().tolist()], y_train_a[indices_a.flatten().tolist()]))
print(lasso_x_train.shape)
print(lasso_y_train.shape)

(18, 121)
(18,)

In [41]:
lasso_classifier = Lasso(alpha=0.01)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
#print(lasso_classifier.coef_)
#print(lasso_classifier.intercept_)

Lasso(alpha=0.01)

In [42]:
sorted_importance = show_importance(lasso_classifier.coef_, feature_names, n_features=10)

[ 13  25   0  71  46  41 120  73  89  32]
Product Type_FX: -0.44062356801067176
Product Class_Cash in / out (withdrawal), Security in / out: 0.43953873509925334
amount_log: -0.17105727996190773
rolling_std_1h: 0.11148772891697573
product_class_index_timestamp_diff_1: -0.10959079743362234
product_type_index_timestamp_diff_1: 0.08762863897469755
Currency_freq_originator: 0.08141598715522942
rolling_std_24h: 0.06801874787144765
rolling_mean_originator_24h: 0.05955602363474946
originator_index_timestamp_diff_2: 0.05845220259692664

In [43]:
imp_features = [feature_names[idx] for idx in sorted_importance]
print(imp_features)
df_test.filter(pl.col('index') == idx).select(imp_features)

['Product Type_FX', 'Product Class_Cash in / out (withdrawal), Security in / out', 'amount_log', 'rolling_std_1h', 'product_class_index_timestamp_diff_1', 'product_type_index_timestamp_diff_1', 'Currency_freq_originator', 'rolling_std_24h', 'rolling_mean_originator_24h', 'originator_index_timestamp_diff_2']

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ Product ┆ Product ┆ amount_ ┆ rolling ┆ product ┆ product ┆ Currenc ┆ rolling ┆ rolling ┆ origin │
│ Type_FX ┆ Class_C ┆ log     ┆ _std_1h ┆ _class_ ┆ _type_i ┆ y_freq_ ┆ _std_24 ┆ _mean_o ┆ ator_i │
│ ---     ┆ ash in  ┆ ---     ┆ ---     ┆ index_t ┆ ndex_ti ┆ origina ┆ h       ┆ riginat ┆ ndex_t │
│ u8      ┆ / out   ┆ f64     ┆ f64     ┆ imestam ┆ mestamp ┆ tor     ┆ ---     ┆ or_24h  ┆ imesta │
│         ┆ (w…     ┆         ┆         ┆ p_…     ┆ _d…     ┆ ---     ┆ f64     ┆ ---     ┆ mp_dif │
│         ┆ ---     ┆         ┆         ┆ ---     ┆ ---     ┆ f64     ┆         ┆ f64     ┆ …      │
│         ┆ u8      ┆         ┆         ┆ f64     ┆ f64     ┆         ┆         ┆         ┆ ---    │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ f64    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ 0       ┆ 1       ┆ -1.3749 ┆ -1.2188 ┆ 2.41095 ┆ -1.3905 ┆ 0.62722 ┆ -2.0994 ┆ -6.9930 ┆ 1.4458 │
│         ┆         ┆ 93      ┆ 32      ┆ 1       ┆ 33      ┆ 5       ┆ 12      ┆ 79      ┆ 17     │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

In [36]:
y_pred = lasso_classifier.predict(x.reshape(1, -1))
print(y_pred)
print('R squared training set', lasso_classifier.score(lasso_x_train, lasso_y_train))

[0.53399728]
R squared training set 0.9712493053772452

In [40]:
lasso_classifier = Lasso(alpha=0.05)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
sorted_importance = show_importance(lasso_classifier.coef_, feature_names, n_features=10)
#print(lasso_classifier.coef_)
#print(lasso_classifier.intercept_)

[  0  13  71  58  41  65  31  46  25 116]
amount_log: -0.22774516507272935
Product Type_FX: -0.20657789590888484
rolling_std_1h: 0.10104766108921424
day_of_month_cos: 0.06589130934568095
product_type_index_timestamp_diff_1: 0.04769999608521683
rolling_mean_24h: 0.045060945086517167
originator_index_timestamp_diff_1: -0.04103741245885048
product_class_index_timestamp_diff_1: -0.02216899866712941
Product Class_Cash in / out (withdrawal), Security in / out: 0.009038137501358446
InputOutput_freq_originator: 0.0038723635540293664

## 2.2. Transactions with rounded normalized amounts bought or sold within an account:
It is unusual for transactions in capital markets to have rounded amounts (unless they occur in markets where foreign exchange conversion causes rounding errors).

In [198]:
anomaly_type = 2
idx = 2762998
#idx = 8891

In [54]:
X_train_a = X_train[y_pred_train == anomaly_type]
y_train_a = y_pred_train[y_pred_train == anomaly_type]
print(X_train_a.shape)
print(y_train_a.shape)

(3075, 121)
(3075,)

In [55]:
x = X_test[idx].reshape(1, -1)

print(x.shape)
print(x[:, :6])
print(y_test[idx])
print(y_pred_test[idx])

(1, 121)
[[-0.15372607  0.          1.          0.          0.          1.        ]]
2
2

In [56]:
df_correct_preds.filter(pl.col("index") == idx)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 276 ┆ 2   ┆ 293 ┆ 201 ┆ Cli ┆ 2   ┆ 1   ┆ -0. ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 25  ┆ 20  ┆ 58  ┆ tru ┆ 1.9 ┆ 1.4 ┆ 1.1 ┆ 1.0 ┆ 0.9 ┆ 1.6 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -1. ┆ -0. ┆ 0.0 ┆ 0.7 ┆ 1.3 ┆ 1.4 ┆ 0.2 ┆ 1.2 ┆ 1.9 ┆ 0.4 ┆ 1.3 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 1.1 ┆ 0.5 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.3 ┆ -0. ┆ -0. ┆ 0.5 ┆ 0.5 ┆ 1.0 ┆ 1.3 ┆ -0. ┆ 1.1 ┆ 0.5 ┆ 0.0 ┆ 1.2 ┆ 0.8 ┆ 0.6 ┆ -0. ┆ 0.8 ┆ 0.4 ┆ 0.3 ┆ -0. ┆ 0.5 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.2 ┆ -0. ┆ 0.2 ┆ 0.7 ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.4 ┆ -0. ┆ 0.0 ┆ 2.6 ┆ -1. ┆ 1.4 ┆ -0. ┆ 0.6 │
│ 299 ┆     ┆ 583 ┆ 9-0 ┆ ent ┆     ┆     ┆ 153 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ 760 ┆ 056 ┆ 832 ┆ 624 ┆ 969 ┆ 665 ┆ 284 ┆ 112 ┆     ┆     ┆ 390 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 433 ┆ 183 ┆ 071 ┆     ┆     ┆ 922 ┆ 812 ┆ 000 ┆ 000 ┆ 170 ┆ 654 ┆ 935 ┆ 762 ┆ 279 ┆ 005 ┆ 370 ┆ 447 ┆ 200 ┆ 763 ┆ 890 ┆ 796 ┆ 016 ┆ 586 ┆ 480 ┆ 141 ┆ 080 ┆ 629 ┆ 678 ┆ 552 ┆ 077 ┆ 986 ┆ 065 ┆ 728 ┆ 213 ┆ 412 ┆ 941 ┆ 870 ┆ 001 ┆ 884 ┆ 774 ┆ 276 ┆ 593 ┆ 395 ┆ 373 ┆ 805 ┆ 411 ┆ 724 ┆ 173 ┆ 329 ┆ 024 ┆ 299 ┆ 218 ┆ 538 ┆ 677 ┆ 033 ┆ 143 ┆ 429 ┆ 000 ┆ 626 ┆ 385 ┆ 922 ┆ 003 ┆ 166 ┆ 562 ┆ 865 ┆ 028 ┆ 798 ┆ 454 ┆ 138 ┆ 690 ┆ 396 ┆ 722 ┆ 956 ┆ 499 ┆ 328 │
│ 8   ┆     ┆ 56  ┆ 3-2 ┆ _12 ┆     ┆     ┆ 726 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 88  ┆ 21  ┆ 06  ┆ 52  ┆ 17  ┆ 01  ┆ 955 ┆ 912 ┆     ┆     ┆ 533 ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 523 ┆ 119 ┆ 133 ┆     ┆     ┆ 82  ┆ 988 ┆ 167 ┆ 56  ┆ 8   ┆ 56  ┆ 61  ┆ 27  ┆ 68  ┆ 58  ┆ 69  ┆ 62  ┆ 75  ┆ 227 ┆ 09  ┆ 219 ┆ 536 ┆ 88  ┆ 16  ┆ 53  ┆ 111 ┆ 587 ┆ 835 ┆ 343 ┆ 862 ┆ 77  ┆ 88  ┆ 241 ┆ 48  ┆ 03  ┆     ┆ 32  ┆ 232 ┆ 33  ┆ 66  ┆ 34  ┆ 45  ┆ 76  ┆ 49  ┆ 479 ┆ 42  ┆ 69  ┆ 98  ┆ 275 ┆ 07  ┆ 35  ┆ 243 ┆ 934 ┆ 05  ┆ 233 ┆ 52  ┆ 84  ┆ 139 ┆ 85  ┆ 41  ┆ 17  ┆ 19  ┆ 196 ┆ 521 ┆ 694 ┆ 408 ┆ 103 ┆ 16  ┆ 752 ┆ 83  ┆ 91  ┆ 951 ┆ 38  ┆ 056 ┆ 01  │
│     ┆     ┆     ┆ 5   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 20: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 58: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 44  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [57]:
knn_normal = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_normal.fit(X_train_n)
distances_n, indices_n = knn_normal.kneighbors(x, n_neighbors=k)
print(indices_n)
print(distances_n)

knn_anomaly = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_anomaly.fit(X_train_a)
distances_a, indices_a = knn_anomaly.kneighbors(x, n_neighbors=k)
print(indices_a)
print(distances_a)

[[ 7500287  7487612 19638126  7498911  7479744  7493992  7496824  7504858
  19634012]]
[[5.33582442 5.57497992 5.62633362 5.63051838 5.6475954  5.70801727
  5.72663683 5.75048922 5.77467883]]
[[2847 2852 2274 1049 2816 1043 2056 1434 2679]]
[[5.39437431 6.37619863 6.57638483 6.58323012 6.65733044 6.74744505
  6.79097108 6.87449587 6.93982183]]

In [58]:
lasso_x_train = np.vstack((X_train_n[indices_n.flatten().tolist()], X_train_a[indices_a.flatten().tolist()]))
lasso_y_train = np.concatenate((y_train_n[indices_n.flatten().tolist()], y_train_a[indices_a.flatten().tolist()]))
print(lasso_x_train.shape)
print(lasso_y_train.shape)
lasso_classifier = Lasso(alpha=0.01)
lasso_classifier.fit(lasso_x_train, lasso_y_train)

(18, 121)
(18,)

Lasso(alpha=0.01)

In [59]:
sorted_importance = show_importance(lasso_classifier.coef_, feature_names, n_features=10)

[ 30  56  82 116  98  79 114 115 120 112]
is_rounded: 1.8373229624261656
day_of_week_cos: -0.038877705878208546
rolling_min_7d: -0.02488240302674951
InputOutput_freq_originator: 0.014420370847847905
rolling_max_originator_7d: -0.007949514242944685
rolling_min_1h: 0.000842879627505212
cumcount_Product Class: 0.0
cumcount_Currency: 0.0
Currency_freq_originator: 0.0
cumcount_Market: 0.0

In [60]:
imp_features = [feature_names[idx] for idx in sorted_importance]
print(imp_features)
df_test.filter(pl.col('index') == idx).select(imp_features)

['is_rounded', 'day_of_week_cos', 'rolling_min_7d', 'InputOutput_freq_originator', 'rolling_max_originator_7d', 'rolling_min_1h', 'cumcount_Product Class', 'cumcount_Currency', 'Currency_freq_originator', 'cumcount_Market']

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ is_roun ┆ day_of_ ┆ rolling ┆ InputOu ┆ rolling ┆ rolling ┆ cumcoun ┆ cumcoun ┆ Currenc ┆ cumcou │
│ ded     ┆ week_co ┆ _min_7d ┆ tput_fr ┆ _max_or ┆ _min_1h ┆ t_Produ ┆ t_Curre ┆ y_freq_ ┆ nt_Mar │
│ ---     ┆ s       ┆ ---     ┆ eq_orig ┆ iginato ┆ ---     ┆ ct      ┆ ncy     ┆ origina ┆ ket    │
│ bool    ┆ ---     ┆ f64     ┆ inator  ┆ r_7d    ┆ f64     ┆ Class   ┆ ---     ┆ tor     ┆ ---    │
│         ┆ f64     ┆         ┆ ---     ┆ ---     ┆         ┆ ---     ┆ f64     ┆ ---     ┆ f64    │
│         ┆         ┆         ┆ f64     ┆ f64     ┆         ┆ f64     ┆         ┆ f64     ┆        │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ true    ┆ 1.36545 ┆ 1.38703 ┆ 2.63969 ┆ -0.5389 ┆ 0.52134 ┆ -0.1387 ┆ 0.06908 ┆ 0.63280 ┆ -0.798 │
│         ┆ 6       ┆ 2       ┆ 1       ┆ 34      ┆ 8       ┆ 52      ┆ 3       ┆ 1       ┆ 103    │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

In [61]:
y_pred = lasso_classifier.predict(x)
print(y_pred)
print('R squared training set', lasso_classifier.score(lasso_x_train, lasso_y_train))

[1.87611121]
R squared training set 0.999236791700946

In [ ]:
#df_correct_preds.filter((pl.col("Anomaly") == 2))

Ale importance transakce 8891:  
[ 62  56  86  85 120  45  94  31  32 105]  
day_of_month_cos: 0.4909162578149944  
market_index_amount_diff_1: -0.2561160148612243  
rolling_min_7d: 0.19531048134345905  
rolling_min_24h: -0.17233210873780314  
InputOutput_freq_originator: 0.15725736811678412  
product_type_index_timestamp_diff_1: 0.12452001855439251  
rolling_mean_originator_7d: -0.09423044080411237  
day_of_month: 0.057788530885468  
hour: -0.05252906617590189  
rolling_min_originator_24h: 0.0374342169108247

## 2.3. Security bought or sold at an unusual time:
It is unusual for clients to trade specific securities outside of a specific timeframe (for example, outside of the opening and closing times of a stock exchange).

In [99]:
anomaly_type = 3
idx = 1260		
X_train_a = X_train[y_pred_train == anomaly_type]
y_train_a = y_pred_train[y_pred_train == anomaly_type]
print(X_train_a.shape)
print(y_train_a.shape)

(11425, 121)
(11425,)

In [100]:
x = X_test[idx].reshape(1, -1)

print(x.shape)
print(x[:, :6])
print(y_test[idx])
print(y_pred_test[idx])

(1, 121)
[[0.29441406 0.         1.         0.         1.         0.        ]]
3
3

In [101]:
df_correct_preds.filter(pl.col("index") == idx)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 126 ┆ 3   ┆ 271 ┆ 201 ┆ Cli ┆ 3   ┆ 1   ┆ 0.2 ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 18  ┆ 2   ┆ 12  ┆ fal ┆ 2.6 ┆ 1.9 ┆ 1.6 ┆ 1.4 ┆ 1.3 ┆ 1.6 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 2.4 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 2.4 ┆ 0.7 ┆ 1.3 ┆ 0.5 ┆ -1. ┆ -0. ┆ 3.6 ┆ -1. ┆ 0.5 ┆ -7. ┆ -4. ┆ -5. ┆ -0. ┆ -7. ┆ -6. ┆ -9. ┆ 0.2 ┆ -6. ┆ -1. ┆ -1. ┆ -0. ┆ -4. ┆ -6. ┆ -6. ┆ -0. ┆ 3.7 ┆ 5.0 ┆ 5.9 ┆ -0. ┆ -7. ┆ -6. ┆ -9. ┆ 0.2 ┆ -1. ┆ -4. ┆ -5. ┆ -1. ┆ -3. ┆ -10 ┆ -13 ┆ -0. ┆ -3. ┆ -9. ┆ -12 ┆ 0.8 ┆ 9.3 ┆ 25. ┆ 26. ┆ 0.8 ┆ -2. ┆ -4. ┆ -5. ┆ -0. ┆ -2. ┆ -3. ┆ -3. ┆ -0. ┆ 0.2 ┆ 0.0 ┆ 0.7 ┆ 0.3 ┆ 0.2 ┆ 5.8 ┆ -0. ┆ 2.1 ┆ 0.2 ┆ 0.6 │
│ 0   ┆     ┆ 783 ┆ 9-0 ┆ ent ┆     ┆     ┆ 944 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 933 ┆ 380 ┆ 042 ┆ 290 ┆ 259 ┆ 201 ┆ 284 ┆ 112 ┆     ┆     ┆ 363 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 106 ┆ 183 ┆ 071 ┆     ┆     ┆ 809 ┆ 947 ┆ 737 ┆ 880 ┆ 170 ┆ 654 ┆ 134 ┆ 287 ┆ 415 ┆ 205 ┆ 291 ┆ 749 ┆ 040 ┆ 478 ┆ 307 ┆ 885 ┆ 668 ┆ 996 ┆ 240 ┆ 058 ┆ 977 ┆ 257 ┆ 373 ┆ 493 ┆ 130 ┆ 054 ┆ 952 ┆ 014 ┆ 607 ┆ 883 ┆ 482 ┆ 372 ┆ 242 ┆ 913 ┆ 156 ┆ 214 ┆ 520 ┆ 596 ┆ 869 ┆ 097 ┆ 273 ┆ .62 ┆ .09 ┆ 096 ┆ 061 ┆ 805 ┆ .26 ┆ 466 ┆ 889 ┆ 046 ┆ 417 ┆ 322 ┆ 255 ┆ 251 ┆ 017 ┆ 635 ┆ 107 ┆ 266 ┆ 916 ┆ 551 ┆ 904 ┆ 989 ┆ 784 ┆ 043 ┆ 914 ┆ 685 ┆ 318 ┆ 703 ┆ 510 ┆ 174 │
│     ┆     ┆ 34  ┆ 3-1 ┆ _06 ┆     ┆     ┆ 14  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 93  ┆ 64  ┆ 63  ┆ 05  ┆ 9   ┆ 1   ┆ 955 ┆ 912 ┆     ┆     ┆ 72  ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 22  ┆ 119 ┆ 133 ┆     ┆     ┆ 817 ┆ 825 ┆ 582 ┆ 78  ┆ 8   ┆ 56  ┆ 69  ┆ 407 ┆ 434 ┆ 74  ┆ 928 ┆ 92  ┆ 985 ┆ 681 ┆ 024 ┆ 715 ┆ 171 ┆ 847 ┆ 966 ┆ 23  ┆ 387 ┆ 678 ┆ 856 ┆ 289 ┆ 003 ┆ 988 ┆ 494 ┆ 74  ┆ 12  ┆ 95  ┆ 32  ┆ 707 ┆ 847 ┆ 582 ┆ 406 ┆ 38  ┆ 532 ┆ 581 ┆ 774 ┆ 352 ┆ 551 ┆ 446 ┆ 860 ┆ 861 ┆ 561 ┆ 656 ┆ 496 ┆ 07  ┆ 72  ┆ 921 ┆ 167 ┆ 07  ┆ 149 ┆ 355 ┆ 756 ┆ 96  ┆ 744 ┆ 43  ┆ 126 ┆ 296 ┆ 56  ┆ 06  ┆ 34  ┆ 75  ┆ 89  ┆ 3   ┆ 561 ┆ 9   ┆ 52  ┆ 51  │
│     ┆     ┆     ┆ 8   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 02: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 12: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 51  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [102]:
knn_normal = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_normal.fit(X_train_n)
distances_n, indices_n = knn_normal.kneighbors(x, n_neighbors=k)
print(indices_n)
print(distances_n)

knn_anomaly = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_anomaly.fit(X_train_a)
distances_a, indices_a = knn_anomaly.kneighbors(x, n_neighbors=k)
print(indices_a)
print(distances_a)

[[7043866 7043354 7043914 7043910 7043558 7043880 7043722 7043337 7043619]]
[[ 9.80910193  9.83282517 10.16924695 10.86467745 10.88809653 10.95037122
  11.10880725 11.11182644 11.14470368]]
[[3645 3690 3679 3686 3681 9436 3696 9439 3692]]
[[8.4496887  8.77086534 8.88993799 8.97371076 9.03059821 9.2971054
  9.364501   9.41529693 9.56759954]]

In [103]:
lasso_x_train = np.vstack((X_train_n[indices_n.flatten().tolist()], X_train_a[indices_a.flatten().tolist()]))
lasso_y_train = np.concatenate((y_train_n[indices_n.flatten().tolist()], y_train_a[indices_a.flatten().tolist()]))
print(lasso_x_train.shape)
print(lasso_y_train.shape)
lasso_classifier = Lasso(alpha=0.01)
lasso_classifier.fit(lasso_x_train, lasso_y_train)

(18, 121)
(18,)

Lasso(alpha=0.01)

In [108]:
sorted_importance = show_importance(lasso_classifier.coef_, feature_names, n_features=10)

[116  65  62  46  98  51  93  36 120 112]
InputOutput_freq_originator: 0.7002027325078276
rolling_mean_24h: 0.44943992992865894
minute_cos: -0.34185366174871246
product_class_index_timestamp_diff_1: 0.19978465253480407
rolling_max_originator_7d: 0.06519587949834159
originator_index_amount_diff_1: -0.04534185307085977
rolling_std_originator_24h: 0.04198310245251187
market_index_timestamp_diff_1: 0.017506986342667206
Currency_freq_originator: -0.0
cumcount_Market: 0.0

In [109]:
imp_features = [feature_names[idx] for idx in sorted_importance[:10]]
print(imp_features)
df_test.filter(pl.col('index') == idx).select(imp_features)

['InputOutput_freq_originator', 'rolling_mean_24h', 'minute_cos', 'product_class_index_timestamp_diff_1', 'rolling_max_originator_7d', 'originator_index_amount_diff_1', 'rolling_std_originator_24h', 'market_index_timestamp_diff_1', 'Currency_freq_originator', 'cumcount_Market']

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ InputOu ┆ rolling ┆ minute_ ┆ product ┆ rolling ┆ origina ┆ rolling ┆ market_ ┆ Currenc ┆ cumcou │
│ tput_fr ┆ _mean_2 ┆ cos     ┆ _class_ ┆ _max_or ┆ tor_ind ┆ _std_or ┆ index_t ┆ y_freq_ ┆ nt_Mar │
│ eq_orig ┆ 4h      ┆ ---     ┆ index_t ┆ iginato ┆ ex_amou ┆ iginato ┆ imestam ┆ origina ┆ ket    │
│ inator  ┆ ---     ┆ f64     ┆ imestam ┆ r_7d    ┆ nt_diff ┆ r_24h   ┆ p_diff_ ┆ tor     ┆ ---    │
│ ---     ┆ f64     ┆         ┆ p_…     ┆ ---     ┆ _1      ┆ ---     ┆ 1       ┆ ---     ┆ f64    │
│ f64     ┆         ┆         ┆ ---     ┆ f64     ┆ ---     ┆ f64     ┆ ---     ┆ f64     ┆        │
│         ┆         ┆         ┆ f64     ┆         ┆ f64     ┆         ┆ f64     ┆         ┆        │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ 5.86853 ┆ -5.3070 ┆ 0.57499 ┆ 2.41062 ┆ 0.84660 ┆ -0.8098 ┆ -13.098 ┆ 1.62011 ┆ 0.61745 ┆ 0.0989 │
│         ┆ 24      ┆ 2       ┆ 2       ┆ 7       ┆ 17      ┆ 606     ┆         ┆ 1       ┆ 06     │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

In [105]:
# Pro alpha = 0.05
lasso_classifier = Lasso(alpha=0.05)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
sorted_importance = show_importance(lasso_classifier.coef_, feature_names, n_features=10)

[116  65  62  46  61  51   4  93 120  98]
InputOutput_freq_originator: 0.7013087267132068
rolling_mean_24h: 0.4454291968333194
minute_cos: -0.34699151384122495
product_class_index_timestamp_diff_1: 0.17918565999176703
minute_sin: -0.14234736344503757
originator_index_amount_diff_1: -0.12232507012927467
Market_2: 0.11441864940632246
rolling_std_originator_24h: 0.06323571192360138
Currency_freq_originator: -0.061281951625473854
rolling_max_originator_7d: 0.02488112078625296

In [106]:
# Pro alpha = 0.1
lasso_classifier = Lasso(alpha=0.1)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
sorted_importance = show_importance(lasso_classifier.coef_, feature_names, n_features=10)

[116  65  62  46  98  51  93  36 120 112]
InputOutput_freq_originator: 0.7002027325078276
rolling_mean_24h: 0.44943992992865894
minute_cos: -0.34185366174871246
product_class_index_timestamp_diff_1: 0.19978465253480407
rolling_max_originator_7d: 0.06519587949834159
originator_index_amount_diff_1: -0.04534185307085977
rolling_std_originator_24h: 0.04198310245251187
market_index_timestamp_diff_1: 0.017506986342667206
Currency_freq_originator: -0.0
cumcount_Market: 0.0

## 2.4. Large asset withdrawal:
A sudden spike in transaction amount withdrawn from an account or transferred out, which deviates from the previous transactional activity and is absent of any commercial rationale or related corporate action event.

In [149]:
anomaly_type = 4
idx = 16483
X_train_a = X_train[y_pred_train == anomaly_type]
y_train_a = y_pred_train[y_pred_train == anomaly_type]
print(X_train_a.shape)
print(y_train_a.shape)

(60973, 121)
(60973,)

In [150]:
x = X_test[idx].reshape(1, -1)

print(x.shape)
print(x[:, :6])
print(y_test[idx])
print(y_pred_test[idx])

(1, 121)
[[0.46960018 0.         1.         0.         0.         0.        ]]
4
4

In [151]:
df_correct_preds.filter(pl.col("index") == idx)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 164 ┆ 4   ┆ 270 ┆ 201 ┆ Cli ┆ 4   ┆ 1   ┆ 0.4 ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 18  ┆ 7   ┆ 21  ┆ fal ┆ 2.6 ┆ 1.9 ┆ 1.6 ┆ 1.4 ┆ 1.3 ┆ 0.8 ┆ 3.6 ┆ 9.1 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ 1.8 ┆ 1.2 ┆ 0.0 ┆ 0.7 ┆ 1.3 ┆ 0.5 ┆ -1. ┆ -1. ┆ 1.2 ┆ -1. ┆ -0. ┆ -0. ┆ -1. ┆ -1. ┆ -0. ┆ -1. ┆ -3. ┆ -5. ┆ 0.2 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -2. ┆ -2. ┆ -0. ┆ 2.1 ┆ 0.7 ┆ 1.2 ┆ -0. ┆ -1. ┆ -3. ┆ -5. ┆ 0.2 ┆ 1.1 ┆ -0. ┆ -0. ┆ -0. ┆ 0.7 ┆ 0.2 ┆ 0.2 ┆ -0. ┆ 0.4 ┆ -0. ┆ -0. ┆ 0.8 ┆ 0.3 ┆ 1.7 ┆ 2.1 ┆ 0.8 ┆ -0. ┆ -1. ┆ -2. ┆ -0. ┆ -1. ┆ -1. ┆ -2. ┆ -0. ┆ 0.2 ┆ -0. ┆ 0.7 ┆ 0.3 ┆ -0. ┆ 5.8 ┆ -1. ┆ 2.1 ┆ 0.2 ┆ -1. │
│ 83  ┆     ┆ 122 ┆ 9-0 ┆ ent ┆     ┆     ┆ 696 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 942 ┆ 386 ┆ 048 ┆ 294 ┆ 264 ┆ 743 ┆ 171 ┆ 432 ┆     ┆     ┆ 370 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 433 ┆ 183 ┆ 071 ┆     ┆     ┆ 023 ┆ 032 ┆ 296 ┆ 000 ┆ 170 ┆ 654 ┆ 134 ┆ 287 ┆ 409 ┆ 709 ┆ 224 ┆ 707 ┆ 280 ┆ 408 ┆ 684 ┆ 895 ┆ 647 ┆ 436 ┆ 080 ┆ 052 ┆ 550 ┆ 471 ┆ 534 ┆ 501 ┆ 652 ┆ 059 ┆ 689 ┆ 014 ┆ 986 ┆ 302 ┆ 958 ┆ 372 ┆ 655 ┆ 418 ┆ 070 ┆ 210 ┆ 262 ┆ 085 ┆ 182 ┆ 941 ┆ 632 ┆ 676 ┆ 246 ┆ 013 ┆ 785 ┆ 067 ┆ 337 ┆ 466 ┆ 924 ┆ 950 ┆ 244 ┆ 322 ┆ 184 ┆ 541 ┆ 135 ┆ 623 ┆ 169 ┆ 663 ┆ 247 ┆ 552 ┆ 917 ┆ 568 ┆ 806 ┆ 055 ┆ 300 ┆ 839 ┆ 708 ┆ 787 ┆ 523 ┆ 595 │
│     ┆     ┆ 63  ┆ 3-1 ┆ _06 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 39  ┆ 99  ┆ 09  ┆ 75  ┆ 25  ┆ 52  ┆ 36  ┆ 2   ┆     ┆     ┆ 95  ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 523 ┆ 119 ┆ 133 ┆     ┆     ┆ 369 ┆ 47  ┆ 54  ┆ 56  ┆ 8   ┆ 56  ┆ 69  ┆ 407 ┆ 974 ┆ 89  ┆ 723 ┆ 304 ┆ 875 ┆ 6   ┆ 538 ┆ 477 ┆ 94  ┆ 343 ┆ 934 ┆ 98  ┆ 42  ┆ 442 ┆ 583 ┆ 066 ┆ 191 ┆ 952 ┆ 448 ┆ 74  ┆ 5   ┆ 3   ┆ 85  ┆ 707 ┆ 346 ┆ 487 ┆ 047 ┆ 8   ┆ 55  ┆ 079 ┆ 283 ┆ 591 ┆ 92  ┆ 73  ┆ 13  ┆ 294 ┆ 99  ┆ 813 ┆ 965 ┆ 07  ┆ 58  ┆ 65  ┆ 89  ┆ 07  ┆ 175 ┆ 056 ┆ 234 ┆ 714 ┆ 972 ┆ 468 ┆ 584 ┆ 075 ┆ 8   ┆ 132 ┆ 85  ┆ 31  ┆ 857 ┆ 99  ┆ 558 ┆ 81  ┆ 04  ┆ 249 │
│     ┆     ┆     ┆ 8   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 07: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 21: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 58  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [152]:
knn_normal = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_normal.fit(X_train_n)
distances_n, indices_n = knn_normal.kneighbors(x, n_neighbors=k)
print(indices_n)
print(distances_n)

knn_anomaly = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_anomaly.fit(X_train_a)
distances_a, indices_a = knn_anomaly.kneighbors(x, n_neighbors=k)
print(indices_a)
print(distances_a)

[[14138205 14135088 11855308 14135887 14147730 11836983 14144681 14148504
  11838074]]
[[8.88116915 8.90100421 9.28912904 9.31328498 9.45472792 9.5022187
  9.54287454 9.56637248 9.57343492]]
[[45052 45443  5854 36790 39608 26430 45723 41654 26385]]
[[ 9.6071285  10.40947282 11.20253104 11.28701603 11.35696534 11.43945213
  11.51885464 11.58405372 11.58416456]]

In [153]:
lasso_x_train = np.vstack((X_train_n[indices_n.flatten().tolist()], X_train_a[indices_a.flatten().tolist()]))
lasso_y_train = np.concatenate((y_train_n[indices_n.flatten().tolist()], y_train_a[indices_a.flatten().tolist()]))
print(lasso_x_train.shape)
print(lasso_y_train.shape)
lasso_classifier = Lasso(alpha=0.01)
lasso_classifier.fit(lasso_x_train, lasso_y_train)

(18, 121)
(18,)

Lasso(alpha=0.01)

In [154]:
sorted_importance = show_importance(lasso_classifier.coef_, feature_names, n_features=10)

[  1  65  68 119 116  58  69   2 115 111]
InputOutput_Buy: -3.8145697144400788
rolling_mean_24h: 0.028400094582235892
rolling_sum_12h: 0.01957081807722386
Product Class_freq_originator: -0.011515917183301576
InputOutput_freq_originator: 0.010195188613114371
day_of_month_cos: -0.0018328419977957386
rolling_sum_24h: 0.0010529616193847367
InputOutput_Sell: 1.1842378929335002e-15
cumcount_Currency: -0.0
cumcount_InputOutput: -0.0

In [155]:
y_pred = lasso_classifier.predict(x)
print(y_pred)
print('R squared training set', lasso_classifier.score(lasso_x_train, lasso_y_train))

[3.89945152]
R squared training set 0.9997168872522549

In [156]:
imp_features = [feature_names[idx] for idx in sorted_importance[:10]]
print(imp_features)
df_test.filter(pl.col('index') == idx).select(imp_features)

['InputOutput_Buy', 'rolling_mean_24h', 'rolling_sum_12h', 'Product Class_freq_originator', 'InputOutput_freq_originator', 'day_of_month_cos', 'rolling_sum_24h', 'InputOutput_Sell', 'cumcount_Currency', 'cumcount_InputOutput']

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ InputOu ┆ rolling ┆ rolling ┆ Product ┆ InputOu ┆ day_of_ ┆ rolling ┆ InputOu ┆ cumcoun ┆ cumcou │
│ tput_Bu ┆ _mean_2 ┆ _sum_12 ┆ Class_f ┆ tput_fr ┆ month_c ┆ _sum_24 ┆ tput_Se ┆ t_Curre ┆ nt_Inp │
│ y       ┆ 4h      ┆ h       ┆ req_ori ┆ eq_orig ┆ os      ┆ h       ┆ ll      ┆ ncy     ┆ utOutp │
│ ---     ┆ ---     ┆ ---     ┆ ginator ┆ inator  ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ut     │
│ u8      ┆ f64     ┆ f64     ┆ ---     ┆ ---     ┆ f64     ┆ f64     ┆ u8      ┆ f64     ┆ ---    │
│         ┆         ┆         ┆ f64     ┆ f64     ┆         ┆         ┆         ┆         ┆ f64    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ 0       ┆ -1.6845 ┆ -3.4363 ┆ 0.25230 ┆ 5.88399 ┆ -1.2874 ┆ -5.0809 ┆ 1       ┆ -0.3008 ┆ 0.2917 │
│         ┆ 38      ┆ 43      ┆ 4       ┆ 9       ┆ 07      ┆ 34      ┆         ┆ 57      ┆ 8      │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

## 2.5. An unusually large amount of collateral transferred in and out of an account within a short period of time:
This behavior is unusual as a client would not be able to invest by simply trading collateral, or at least such a strategy would be unusual.

In [175]:
idx = 37661 #2762376
anomaly_type = 5
X_train_a = X_train[y_pred_train == anomaly_type]
y_train_a = y_pred_train[y_pred_train == anomaly_type]
print(X_train_a.shape)
print(y_train_a.shape)

(68173, 121)
(68173,)

In [176]:
x = X_test[idx].reshape(1, -1)

print(x.shape)
print(x[:, :6])
print(y_test[idx])
print(y_pred_test[idx])

(1, 121)
[[-0.05676139  1.          0.          1.          0.          0.        ]]
5
5

In [161]:
df_correct_preds.filter(pl.col("index") == 2762376)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 276 ┆ 5   ┆ 293 ┆ 201 ┆ Cli ┆ 5   ┆ 1   ┆ 0.3 ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 25  ┆ 20  ┆ 57  ┆ fal ┆ 2.7 ┆ 1.9 ┆ 1.6 ┆ 1.4 ┆ 1.3 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 2.4 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 0.7 ┆ -0. ┆ -1. ┆ -2. ┆ 0.7 ┆ 1.3 ┆ 1.4 ┆ 0.2 ┆ 1.2 ┆ 1.9 ┆ 0.5 ┆ 1.2 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 1.1 ┆ 0.5 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.3 ┆ -0. ┆ -0. ┆ 0.5 ┆ 0.5 ┆ 1.0 ┆ 1.3 ┆ 0.0 ┆ 1.1 ┆ 0.5 ┆ 0.0 ┆ -0. ┆ 0.0 ┆ -0. ┆ -1. ┆ 0.1 ┆ 0.1 ┆ -0. ┆ -0. ┆ 0.2 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.1 ┆ 0.3 ┆ 1.4 ┆ 0.1 ┆ 0.1 ┆ -0. ┆ -0. ┆ 0.2 ┆ 0.1 ┆ -0. ┆ -0. ┆ -0. ┆ 0.1 ┆ 0.4 ┆ 0.3 ┆ 0.3 ┆ -6. ┆ -0. ┆ 0.2 ┆ 0.2 ┆ 0.6 │
│ 237 ┆     ┆ 151 ┆ 9-0 ┆ ent ┆     ┆     ┆ 138 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 229 ┆ 604 ┆ 227 ┆ 450 ┆ 404 ┆ 669 ┆ 284 ┆ 112 ┆     ┆     ┆ 447 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 207 ┆ 183 ┆ 071 ┆     ┆     ┆ 424 ┆ 000 ┆ 474 ┆ 090 ┆ 170 ┆ 654 ┆ 935 ┆ 762 ┆ 279 ┆ 005 ┆ 752 ┆ 917 ┆ 404 ┆ 763 ┆ 902 ┆ 807 ┆ 018 ┆ 593 ┆ 459 ┆ 138 ┆ 303 ┆ 628 ┆ 687 ┆ 560 ┆ 077 ┆ 986 ┆ 065 ┆ 728 ┆ 213 ┆ 412 ┆ 941 ┆ 870 ┆ 132 ┆ 891 ┆ 757 ┆ 275 ┆ 083 ┆ 720 ┆ 167 ┆ 387 ┆ 775 ┆ 244 ┆ 028 ┆ 669 ┆ 932 ┆ 941 ┆ 139 ┆ 921 ┆ 515 ┆ 217 ┆ 762 ┆ 246 ┆ 064 ┆ 760 ┆ 260 ┆ 690 ┆ 133 ┆ 707 ┆ 244 ┆ 582 ┆ 022 ┆ 565 ┆ 022 ┆ 575 ┆ 524 ┆ 525 ┆ 320 ┆ 633 ┆ 485 ┆ 207 │
│ 6   ┆     ┆ 21  ┆ 3-2 ┆ _06 ┆     ┆     ┆ 46  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆ 68  ┆ 18  ┆ 76  ┆ 54  ┆ 069 ┆ 955 ┆ 912 ┆     ┆     ┆ 8   ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 29  ┆ 119 ┆ 133 ┆     ┆     ┆ 09  ┆ 208 ┆ 181 ┆ 58  ┆ 8   ┆ 56  ┆ 61  ┆ 27  ┆ 68  ┆ 58  ┆ 68  ┆ 15  ┆ 574 ┆ 154 ┆ 047 ┆ 294 ┆ 51  ┆ 93  ┆ 71  ┆ 75  ┆ 686 ┆ 762 ┆ 464 ┆ 37  ┆ 862 ┆ 77  ┆ 88  ┆ 241 ┆ 48  ┆ 03  ┆     ┆ 32  ┆ 97  ┆ 63  ┆ 43  ┆ 41  ┆ 594 ┆ 28  ┆ 31  ┆ 996 ┆ 23  ┆ 26  ┆ 279 ┆ 967 ┆ 82  ┆ 48  ┆ 594 ┆ 833 ┆ 97  ┆ 36  ┆ 58  ┆ 29  ┆ 87  ┆ 58  ┆ 982 ┆ 798 ┆ 21  ┆ 81  ┆ 745 ┆ 224 ┆ 088 ┆ 68  ┆ 69  ┆ 33  ┆ 75  ┆ 7   ┆ 222 ┆ 91  ┆ 25  ┆ 35  │
│     ┆     ┆     ┆ 5   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 20: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 57: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 30  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [162]:
df_correct_preds.filter(pl.col("index") == 37661)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 376 ┆ 5   ┆ 272 ┆ 201 ┆ Cli ┆ 5   ┆ 1   ┆ -0. ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 18  ┆ 8   ┆ 0   ┆ fal ┆ 2.7 ┆ 1.9 ┆ 1.6 ┆ 1.4 ┆ 1.3 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.3 ┆ 1.7 ┆ 2.0 ┆ -0. ┆ 2.4 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ 1.1 ┆ -2. ┆ 0.7 ┆ 1.3 ┆ 0.5 ┆ -1. ┆ -1. ┆ 0.6 ┆ 0.1 ┆ 1.4 ┆ 0.5 ┆ 0.3 ┆ 0.3 ┆ -0. ┆ 0.1 ┆ -2. ┆ -3. ┆ 0.2 ┆ 0.4 ┆ 0.2 ┆ 0.2 ┆ -0. ┆ -0. ┆ -1. ┆ -2. ┆ -0. ┆ 0.3 ┆ 0.7 ┆ 1.2 ┆ -0. ┆ 0.0 ┆ -2. ┆ -3. ┆ 0.2 ┆ 0.4 ┆ 1.8 ┆ 2.2 ┆ 0.2 ┆ 0.6 ┆ 1.4 ┆ 1.6 ┆ 0.2 ┆ 0.6 ┆ 0.3 ┆ 0.1 ┆ -0. ┆ 0.0 ┆ 0.8 ┆ 1.1 ┆ 0.6 ┆ -0. ┆ -1. ┆ -1. ┆ -0. ┆ -0. ┆ -1. ┆ -2. ┆ -0. ┆ 0.0 ┆ 0.3 ┆ -0. ┆ -0. ┆ 0.2 ┆ 0.5 ┆ 0.8 ┆ -1. ┆ -1. ┆ 0.6 │
│ 61  ┆     ┆ 670 ┆ 9-0 ┆ ent ┆     ┆     ┆ 056 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 064 ┆ 479 ┆ 124 ┆ 361 ┆ 324 ┆ 669 ┆ 284 ┆ 112 ┆     ┆     ┆ 977 ┆ 929 ┆ 332 ┆ 151 ┆ 484 ┆ 109 ┆ 183 ┆ 071 ┆     ┆     ┆ 984 ┆ 000 ┆ 135 ┆ 277 ┆ 170 ┆ 654 ┆ 134 ┆ 287 ┆ 364 ┆ 414 ┆ 478 ┆ 062 ┆ 409 ┆ 513 ┆ 921 ┆ 925 ┆ 367 ┆ 270 ┆ 718 ┆ 04  ┆ 326 ┆ 798 ┆ 674 ┆ 528 ┆ 272 ┆ 619 ┆ 218 ┆ 014 ┆ 545 ┆ 302 ┆ 958 ┆ 372 ┆ 960 ┆ 295 ┆ 756 ┆ 202 ┆ 473 ┆ 476 ┆ 542 ┆ 933 ┆ 636 ┆ 239 ┆ 389 ┆ 160 ┆ 301 ┆ 490 ┆ 725 ┆ 136 ┆ 041 ┆ 201 ┆ 058 ┆ 689 ┆ 136 ┆ 186 ┆ 758 ┆ 528 ┆ 574 ┆ 805 ┆ 395 ┆ 560 ┆ 804 ┆ 490 ┆ 543 ┆ 460 ┆ 281 ┆ 420 ┆ 737 ┆ 198 ┆ 426 ┆ 187 │
│     ┆     ┆ 59  ┆ 3-1 ┆ _26 ┆     ┆     ┆ 761 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 88  ┆ 68  ┆ 74  ┆ 45  ┆ 26  ┆ 069 ┆ 955 ┆ 912 ┆     ┆     ┆ 52  ┆ 18  ┆ 95  ┆ 49  ┆ 611 ┆ 97  ┆ 119 ┆ 133 ┆     ┆     ┆ 395 ┆ 208 ┆ 91  ┆ 635 ┆ 8   ┆ 56  ┆ 69  ┆ 407 ┆ 252 ┆ 2   ┆ 73  ┆ 3   ┆ 15  ┆ 8   ┆ 18  ┆ 693 ┆ 32  ┆ 245 ┆ 484 ┆     ┆ 96  ┆ 92  ┆ 33  ┆ 028 ┆ 026 ┆ 076 ┆ 995 ┆ 74  ┆ 26  ┆ 3   ┆ 85  ┆ 707 ┆ 5   ┆ 363 ┆ 924 ┆ 9   ┆ 69  ┆ 62  ┆ 54  ┆ 59  ┆ 58  ┆ 71  ┆ 92  ┆ 09  ┆ 39  ┆ 25  ┆ 82  ┆ 32  ┆ 47  ┆ 08  ┆ 91  ┆ 05  ┆ 421 ┆ 503 ┆ 151 ┆ 565 ┆ 383 ┆ 357 ┆ 277 ┆ 217 ┆ 18  ┆ 2   ┆ 534 ┆ 585 ┆ 54  ┆ 62  ┆ 14  ┆ 617 ┆ 166 ┆ 54  │
│     ┆     ┆     ┆ 8   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 08: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 06  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [177]:
knn_normal = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_normal.fit(X_train_n)
distances_n, indices_n = knn_normal.kneighbors(x, n_neighbors=k)
print(indices_n)
print(distances_n)

knn_anomaly = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_anomaly.fit(X_train_a)
distances_a, indices_a = knn_anomaly.kneighbors(x, n_neighbors=k)
print(indices_a)
print(distances_a)

[[21808797 16848393 11909298 14165864 11900477 16845152 11902233 14172080
  19210457]]
[[5.97221627 6.12604803 6.21125437 6.22671549 6.33028924 6.42095239
  6.42564523 6.43306315 6.51636174]]
[[64257 56575 56851 57051 64249 56429 50186 57147 50328]]
[[6.26033484 6.34928418 6.44157577 6.44399835 6.46945057 6.53568155
  6.61234576 6.62052969 6.63836741]]

In [178]:
lasso_x_train = np.vstack((X_train_n[indices_n.flatten().tolist()], X_train_a[indices_a.flatten().tolist()]))
lasso_y_train = np.concatenate((y_train_n[indices_n.flatten().tolist()], y_train_a[indices_a.flatten().tolist()]))
print(lasso_x_train.shape)
print(lasso_y_train.shape)
lasso_classifier = Lasso(alpha=0.01)
lasso_classifier.fit(lasso_x_train, lasso_y_train)

(18, 121)
(18,)

Lasso(alpha=0.01)

In [173]:
# id = 2762376
sorted_importance = show_importance(lasso_classifier.coef_, feature_names, n_features=10)

[ 46  54  78  61 119 115 118 117 116 111]
product_class_index_timestamp_diff_1: 1.728415672604561
product_class_index_amount_diff_1: -0.08604077684077303
rolling_max_7d: -0.018608134257282374
minute_sin: -0.0014934346638327844
Product Class_freq_originator: 0.0
cumcount_Currency: -0.0
Product Type_freq_originator: -0.0
Market_freq_originator: 0.0
InputOutput_freq_originator: -0.0
cumcount_InputOutput: -0.0

In [166]:
# id = 37661
sorted_importance = show_importance(lasso_classifier.coef_, feature_names, n_features=10)

[ 18  73  25   8 109 116  46  31  44  51]
Product Type_FutureEquity: 2.7341464131427853
rolling_std_24h: 2.403818357595594
Product Class_Cash in / out (withdrawal), Security in / out: 2.0495135948153917
Product Type_Bond: -1.759848693811727
rolling_n_transactions_originator_24h: -1.5875966002566642
InputOutput_freq_originator: -1.3203312943447312
product_class_index_timestamp_diff_1: -0.7366671992633759
originator_index_timestamp_diff_1: -0.47146439591708034
product_type_index_timestamp_diff_4: 0.44859961751598837
originator_index_amount_diff_1: -0.34958264889641805

In [167]:
y_pred = lasso_classifier.predict(x)
print(y_pred)
print('R squared training set', lasso_classifier.score(lasso_x_train, lasso_y_train))

[1.45425859]
R squared training set 0.9986235820448766

In [174]:
# index = 2762376
imp_features = [feature_names[idx] for idx in sorted_importance[:10]]
print(imp_features)
df_test.filter(pl.col('index') == idx).select(imp_features)

['product_class_index_timestamp_diff_1', 'product_class_index_amount_diff_1', 'rolling_max_7d', 'minute_sin', 'Product Class_freq_originator', 'cumcount_Currency', 'Product Type_freq_originator', 'Market_freq_originator', 'InputOutput_freq_originator', 'cumcount_InputOutput']

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ product ┆ product ┆ rolling ┆ minute_ ┆ Product ┆ cumcoun ┆ Product ┆ Market_ ┆ InputOu ┆ cumcou │
│ _class_ ┆ _class_ ┆ _max_7d ┆ sin     ┆ Class_f ┆ t_Curre ┆ Type_fr ┆ freq_or ┆ tput_fr ┆ nt_Inp │
│ index_t ┆ index_a ┆ ---     ┆ ---     ┆ req_ori ┆ ncy     ┆ eq_orig ┆ iginato ┆ eq_orig ┆ utOutp │
│ imestam ┆ mount_d ┆ f64     ┆ f64     ┆ ginator ┆ ---     ┆ inator  ┆ r       ┆ inator  ┆ ut     │
│ p_…     ┆ if…     ┆         ┆         ┆ ---     ┆ f64     ┆ ---     ┆ ---     ┆ ---     ┆ ---    │
│ ---     ┆ ---     ┆         ┆         ┆ f64     ┆         ┆ f64     ┆ f64     ┆ f64     ┆ f64    │
│ f64     ┆ f64     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ 2.42072 ┆ -2.0905 ┆ -0.7282 ┆ 0.57526 ┆ 0.24852 ┆ 0.35247 ┆ 0.26339 ┆ -0.3202 ┆ -6.5257 ┆ -0.022 │
│ 9       ┆ 8       ┆ 41      ┆ 8       ┆ 5       ┆ 5       ┆ 1       ┆ 22      ┆         ┆ 088    │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

In [168]:
# idx = 37661
imp_features = [feature_names[idx] for idx in sorted_importance[:10]]
print(imp_features)
df_test.filter(pl.col('index') == idx).select(imp_features)

['Product Type_FutureEquity', 'rolling_std_24h', 'Product Class_Cash in / out (withdrawal), Security in / out', 'Product Type_Bond', 'rolling_n_transactions_originator_24h', 'InputOutput_freq_originator', 'product_class_index_timestamp_diff_1', 'originator_index_timestamp_diff_1', 'product_type_index_timestamp_diff_4', 'originator_index_amount_diff_1']

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ Product ┆ rolling ┆ Product ┆ Product ┆ rolling ┆ InputOu ┆ product ┆ origina ┆ product ┆ origin │
│ Type_Fu ┆ _std_24 ┆ Class_C ┆ Type_Bo ┆ _n_tran ┆ tput_fr ┆ _class_ ┆ tor_ind ┆ _type_i ┆ ator_i │
│ tureEqu ┆ h       ┆ ash in  ┆ nd      ┆ saction ┆ eq_orig ┆ index_t ┆ ex_time ┆ ndex_ti ┆ ndex_a │
│ ity     ┆ ---     ┆ / out   ┆ ---     ┆ s_origi ┆ inator  ┆ imestam ┆ stamp_d ┆ mestamp ┆ mount_ │
│ ---     ┆ f64     ┆ (w…     ┆ u8      ┆ na…     ┆ ---     ┆ p_…     ┆ if…     ┆ _d…     ┆ diff_1 │
│ u8      ┆         ┆ ---     ┆         ┆ ---     ┆ f64     ┆ ---     ┆ ---     ┆ ---     ┆ ---    │
│         ┆         ┆ u8      ┆         ┆ f64     ┆         ┆ f64     ┆ f64     ┆ f64     ┆ f64    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ 0       ┆ 0.26743 ┆ 1       ┆ 0       ┆ -2.3952 ┆ 0.54206 ┆ 2.41099 ┆ 2.70648 ┆ 2.01514 ┆ -0.984 │
│         ┆ 3       ┆         ┆         ┆ 77      ┆ 2       ┆ 7       ┆ 8       ┆ 9       ┆ 395    │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

# 3. Explanations on input space

In [182]:
z_train_n = z_train[y_pred_train == 0]
y_train_n = y_pred_train[y_pred_train == 0]
print(z_train_n.shape)
print(y_train_n.shape)

(24291851, 16)
(24291851,)

## 3.1. Small but highly frequent transactions generated within a short timeframe:
A pattern that contains multiple transactions below applicable reporting thresholds.

In [398]:
anomaly_type = 1
#idx = 8357	
#idx = 47208
#idx = 59510
#idx = 51542
k = 9

In [399]:
z_train_a = z_train[y_pred_train == anomaly_type]
y_train_a = y_pred_train[y_pred_train == anomaly_type]
print(z_train_a.shape)
print(y_train_a.shape)

(16437, 16)
(16437,)

In [400]:
x = torch.tensor(X_test[idx], dtype=torch.float32).reshape(1, -1)
#x = X_test[idx].reshape(1, -1)

print(x.shape)
print(x[:, :6])
print(y_test[idx])
print(y_pred_test[idx])

model.encoder.eval()
test_transaction_latent = model.encoder(x)
test_transaction_latent = test_transaction_latent.cpu().detach().numpy()
test_transaction_latent = test_transaction_latent.reshape(1, -1)
test_transaction_latent.shape

torch.Size([1, 121])
tensor([[-1.3714,  1.0000,  0.0000,  0.0000,  0.0000,  0.0000]])
1
1

(1, 16)

In [393]:
df_correct_preds.filter(pl.col("index") == idx)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 595 ┆ 1   ┆ 273 ┆ 201 ┆ Cli ┆ 1   ┆ 1   ┆ -1. ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 18  ┆ 8   ┆ 38  ┆ fal ┆ 2.1 ┆ 1.9 ┆ 1.6 ┆ 1.4 ┆ 1.3 ┆ 1.6 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -1. ┆ -0. ┆ 0.0 ┆ 0.7 ┆ 1.3 ┆ 0.5 ┆ -1. ┆ -1. ┆ 0.6 ┆ 0.9 ┆ -1. ┆ 0.7 ┆ 0.3 ┆ 0.4 ┆ -0. ┆ 0.1 ┆ -1. ┆ -2. ┆ 0.2 ┆ 0.7 ┆ 0.5 ┆ 0.5 ┆ -0. ┆ 0.5 ┆ -0. ┆ -1. ┆ -0. ┆ -0. ┆ 0.3 ┆ 0.8 ┆ -0. ┆ 0.0 ┆ -1. ┆ -3. ┆ 0.2 ┆ 0.6 ┆ 1.1 ┆ 1.3 ┆ 0.2 ┆ 0.6 ┆ 0.9 ┆ 1.0 ┆ 0.1 ┆ 0.6 ┆ 0.3 ┆ 0.1 ┆ -0. ┆ 0.1 ┆ 0.8 ┆ 1.1 ┆ 0.6 ┆ 0.2 ┆ -0. ┆ -1. ┆ -0. ┆ -0. ┆ -1. ┆ -1. ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.3 ┆ -0. ┆ 0.2 ┆ 0.5 ┆ -1. ┆ 0.5 ┆ -1. ┆ 0.6 │
│ 10  ┆     ┆ 758 ┆ 9-0 ┆ ent ┆     ┆     ┆ 407 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 923 ┆ 480 ┆ 125 ┆ 361 ┆ 324 ┆ 611 ┆ 284 ┆ 112 ┆     ┆     ┆ 390 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 433 ┆ 183 ┆ 071 ┆     ┆     ┆ 069 ┆ 788 ┆ 000 ┆ 000 ┆ 170 ┆ 654 ┆ 134 ┆ 287 ┆ 364 ┆ 414 ┆ 463 ┆ 051 ┆ 241 ┆ 600 ┆ 023 ┆ 895 ┆ 548 ┆ 651 ┆ 996 ┆ 040 ┆ 967 ┆ 110 ┆ 141 ┆ 507 ┆ 560 ┆ 658 ┆ 194 ┆ 014 ┆ 960 ┆ 303 ┆ 690 ┆ 372 ┆ 997 ┆ 673 ┆ 029 ┆ 197 ┆ 373 ┆ 630 ┆ 911 ┆ 607 ┆ 199 ┆ 249 ┆ 286 ┆ 620 ┆ 301 ┆ 490 ┆ 725 ┆ 136 ┆ 740 ┆ 201 ┆ 058 ┆ 689 ┆ 524 ┆ 838 ┆ 387 ┆ 523 ┆ 138 ┆ 241 ┆ 808 ┆ 552 ┆ 814 ┆ 631 ┆ 822 ┆ 456 ┆ 292 ┆ 378 ┆ 711 ┆ 810 ┆ 422 ┆ 187 │
│     ┆     ┆ 15  ┆ 3-1 ┆ _26 ┆     ┆     ┆ 66  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 13  ┆ 54  ┆ 04  ┆ 7   ┆ 52  ┆ 13  ┆ 955 ┆ 912 ┆     ┆     ┆ 533 ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 523 ┆ 119 ┆ 133 ┆     ┆     ┆ 59  ┆ 361 ┆ 167 ┆ 56  ┆ 8   ┆ 56  ┆ 69  ┆ 407 ┆ 252 ┆ 2   ┆ 55  ┆ 156 ┆ 29  ┆ 25  ┆ 19  ┆ 129 ┆ 32  ┆ 899 ┆ 019 ┆ 21  ┆ 84  ┆ 6   ┆ 95  ┆ 972 ┆ 32  ┆ 778 ┆ 275 ┆ 74  ┆ 54  ┆ 61  ┆ 25  ┆ 707 ┆ 18  ┆ 346 ┆ 681 ┆ 93  ┆ 56  ┆ 51  ┆ 89  ┆ 87  ┆ 62  ┆ 63  ┆ 07  ┆ 84  ┆ 39  ┆ 25  ┆ 82  ┆ 32  ┆ 55  ┆ 08  ┆ 91  ┆ 05  ┆ 84  ┆ 063 ┆ 571 ┆ 552 ┆ 612 ┆ 682 ┆ 542 ┆ 387 ┆     ┆ 869 ┆ 31  ┆ 977 ┆ 15  ┆ 78  ┆ 743 ┆ 78  ┆ 436 ┆ 42  │
│     ┆     ┆     ┆ 8   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 08: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 38: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 54  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [401]:
knn_normal = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_normal.fit(z_train_n)
distances_n, indices_n = knn_normal.kneighbors(test_transaction_latent, n_neighbors=k)
print(indices_n)
print(distances_n)

knn_anomaly = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_anomaly.fit(z_train_a)
distances_a, indices_a = knn_anomaly.kneighbors(test_transaction_latent, n_neighbors=k)
print(indices_a)
print(distances_a)

[[ 8469041   786623 14386848 16456170  1653971 14270323  2600641  6884144
    637531]]
[[5.34924221 5.54619646 5.6588006  5.72003078 5.72298956 5.72617292
  5.77509403 5.79466438 5.8052392 ]]
[[ 5630  5573 13153 12428  5596  5594 13160  5592  4047]]
[[1.00450015 1.06799412 1.07400823 1.0847646  1.17012119 1.17083704
  1.22067535 1.24128497 1.25460839]]

In [402]:
lasso_x_train = np.vstack((z_train_n[indices_n.flatten().tolist()], z_train_a[indices_a.flatten().tolist()]))
lasso_y_train = np.concatenate((y_train_n[indices_n.flatten().tolist()], y_train_a[indices_a.flatten().tolist()]))

print(lasso_x_train.shape)
print(lasso_y_train.shape)

(18, 16)
(18,)

In [403]:
lasso_classifier = Lasso(alpha=0.05)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
print(lasso_classifier.coef_)
#print(lasso_classifier.intercept_)

[ 0.0273791   0.         -0.10534227  0.         -0.          0.
 -0.         -0.         -0.          0.          0.19681309 -0.
  0.         -0.         -0.10328226  0.        ]

In [195]:
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[ 4  7 13  8 10  0 11  1 15  9]
z_4: -2.842630624771118
z_7: -1.797913908958435
z_13: -1.7776914834976196
z_8: -0.8401194214820862
z_10: 0.7909547090530396
z_0: -0.6901487708091736
z_11: -0.5478876233100891
z_1: 0.5196952819824219
z_15: -0.3222387135028839
z_9: -0.0

In [381]:
#idx = 47208
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[13 14 10  4 12 11  9 15  8  7]
z_13: -0.399502694606781
z_14: -0.183762788772583
z_10: 0.12452422827482224
z_4: -0.0983685553073883
z_12: 0.0
z_11: -0.0
z_9: 0.0
z_15: -0.0
z_8: -0.0
z_7: -0.0

In [397]:
#idx = 59510
# 59510 a 47208 - stejny klient - vysvetleni jsou podobna
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[13 14 10 15 12 11  9  8  7  6]
z_13: -0.624029815196991
z_14: -0.10480958968400955
z_10: 0.057289741933345795
z_15: 0.0
z_12: -0.0
z_11: -0.0
z_9: 0.0
z_8: -0.0
z_7: -0.0
z_6: 0.0

In [404]:
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[10  2 14  0 12 11 13 15  8  9]
z_10: 0.19681309163570404
z_2: -0.10534226894378662
z_14: -0.10328225791454315
z_0: 0.027379101142287254
z_12: 0.0
z_11: -0.0
z_13: -0.0
z_15: 0.0
z_8: -0.0
z_9: 0.0

In [197]:
y_pred = lasso_classifier.predict(test_transaction_latent)
print(y_pred)
print('R squared training set', lasso_classifier.score(lasso_x_train, lasso_y_train))

[3.9602852]
R squared training set 0.7354124784469604

## 3.2. Transactions with rounded normalized amounts bought or sold within an account:
It is unusual for transactions in capital markets to have rounded amounts (unless they occur in markets where foreign exchange conversion causes rounding errors).

In [253]:
anomaly_type = 2
idx = 2762998
#idx = 8891
#idx = 9186

In [254]:
z_train_a = z_train[y_pred_train == anomaly_type]
y_train_a = y_pred_train[y_pred_train == anomaly_type]
print(z_train_a.shape)
print(y_train_a.shape)

(3075, 16)
(3075,)

In [255]:
x = torch.tensor(X_test[idx], dtype=torch.float32).reshape(1, -1)
#x = X_test[idx].reshape(1, -1)

print(x.shape)
print(x[:, :6])
print(y_test[idx])
print(y_pred_test[idx])

model.encoder.eval()
test_transaction_latent = model.encoder(x)
test_transaction_latent = test_transaction_latent.cpu().detach().numpy()
test_transaction_latent = test_transaction_latent.reshape(1, -1)
test_transaction_latent.shape

torch.Size([1, 121])
tensor([[-0.1537,  0.0000,  1.0000,  0.0000,  0.0000,  1.0000]])
2
2

(1, 16)

In [256]:
df_correct_preds.filter(pl.col("index") == idx)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 276 ┆ 2   ┆ 293 ┆ 201 ┆ Cli ┆ 2   ┆ 1   ┆ -0. ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 25  ┆ 20  ┆ 58  ┆ tru ┆ 1.9 ┆ 1.4 ┆ 1.1 ┆ 1.0 ┆ 0.9 ┆ 1.6 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -1. ┆ -0. ┆ 0.0 ┆ 0.7 ┆ 1.3 ┆ 1.4 ┆ 0.2 ┆ 1.2 ┆ 1.9 ┆ 0.4 ┆ 1.3 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 1.1 ┆ 0.5 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.3 ┆ -0. ┆ -0. ┆ 0.5 ┆ 0.5 ┆ 1.0 ┆ 1.3 ┆ -0. ┆ 1.1 ┆ 0.5 ┆ 0.0 ┆ 1.2 ┆ 0.8 ┆ 0.6 ┆ -0. ┆ 0.8 ┆ 0.4 ┆ 0.3 ┆ -0. ┆ 0.5 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.2 ┆ -0. ┆ 0.2 ┆ 0.7 ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.4 ┆ -0. ┆ 0.0 ┆ 2.6 ┆ -1. ┆ 1.4 ┆ -0. ┆ 0.6 │
│ 299 ┆     ┆ 583 ┆ 9-0 ┆ ent ┆     ┆     ┆ 153 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ 760 ┆ 056 ┆ 832 ┆ 624 ┆ 969 ┆ 665 ┆ 284 ┆ 112 ┆     ┆     ┆ 390 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 433 ┆ 183 ┆ 071 ┆     ┆     ┆ 922 ┆ 812 ┆ 000 ┆ 000 ┆ 170 ┆ 654 ┆ 935 ┆ 762 ┆ 279 ┆ 005 ┆ 370 ┆ 447 ┆ 200 ┆ 763 ┆ 890 ┆ 796 ┆ 016 ┆ 586 ┆ 480 ┆ 141 ┆ 080 ┆ 629 ┆ 678 ┆ 552 ┆ 077 ┆ 986 ┆ 065 ┆ 728 ┆ 213 ┆ 412 ┆ 941 ┆ 870 ┆ 001 ┆ 884 ┆ 774 ┆ 276 ┆ 593 ┆ 395 ┆ 373 ┆ 805 ┆ 411 ┆ 724 ┆ 173 ┆ 329 ┆ 024 ┆ 299 ┆ 218 ┆ 538 ┆ 677 ┆ 033 ┆ 143 ┆ 429 ┆ 000 ┆ 626 ┆ 385 ┆ 922 ┆ 003 ┆ 166 ┆ 562 ┆ 865 ┆ 028 ┆ 798 ┆ 454 ┆ 138 ┆ 690 ┆ 396 ┆ 722 ┆ 956 ┆ 499 ┆ 328 │
│ 8   ┆     ┆ 56  ┆ 3-2 ┆ _12 ┆     ┆     ┆ 726 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 88  ┆ 21  ┆ 06  ┆ 52  ┆ 17  ┆ 01  ┆ 955 ┆ 912 ┆     ┆     ┆ 533 ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 523 ┆ 119 ┆ 133 ┆     ┆     ┆ 82  ┆ 988 ┆ 167 ┆ 56  ┆ 8   ┆ 56  ┆ 61  ┆ 27  ┆ 68  ┆ 58  ┆ 69  ┆ 62  ┆ 75  ┆ 227 ┆ 09  ┆ 219 ┆ 536 ┆ 88  ┆ 16  ┆ 53  ┆ 111 ┆ 587 ┆ 835 ┆ 343 ┆ 862 ┆ 77  ┆ 88  ┆ 241 ┆ 48  ┆ 03  ┆     ┆ 32  ┆ 232 ┆ 33  ┆ 66  ┆ 34  ┆ 45  ┆ 76  ┆ 49  ┆ 479 ┆ 42  ┆ 69  ┆ 98  ┆ 275 ┆ 07  ┆ 35  ┆ 243 ┆ 934 ┆ 05  ┆ 233 ┆ 52  ┆ 84  ┆ 139 ┆ 85  ┆ 41  ┆ 17  ┆ 19  ┆ 196 ┆ 521 ┆ 694 ┆ 408 ┆ 103 ┆ 16  ┆ 752 ┆ 83  ┆ 91  ┆ 951 ┆ 38  ┆ 056 ┆ 01  │
│     ┆     ┆     ┆ 5   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 20: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 58: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 44  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [257]:
knn_normal = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_normal.fit(z_train_n)
distances_n, indices_n = knn_normal.kneighbors(test_transaction_latent, n_neighbors=k)
print(indices_n)
print(distances_n)

knn_anomaly = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_anomaly.fit(z_train_a)
distances_a, indices_a = knn_anomaly.kneighbors(test_transaction_latent, n_neighbors=k)
print(indices_a)
print(distances_a)

[[ 7024447 16785908 15389272 17173201 18709443  1985380 13342260 10973830
  22879734]]
[[2.38548064 2.74158287 2.77904725 2.78241467 2.7916584  2.81790018
  2.83059764 2.8639226  2.88578558]]
[[2003 1680 2585 2584 2852 2334 2028 2609 2331]]
[[1.31661534 1.47595024 1.56430936 1.58656859 1.62715888 1.63853288
  1.68013847 1.69776201 1.70690382]]

In [258]:
lasso_x_train = np.vstack((z_train_n[indices_n.flatten().tolist()], z_train_a[indices_a.flatten().tolist()]))
lasso_y_train = np.concatenate((y_train_n[indices_n.flatten().tolist()], y_train_a[indices_a.flatten().tolist()]))

print(lasso_x_train.shape)
print(lasso_y_train.shape)

(18, 16)
(18,)

In [214]:
# idx = 8891
lasso_classifier = Lasso(alpha=0.1)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
print(lasso_classifier.coef_)
#print(lasso_classifier.intercept_)

[-0.          0.         -0.         -0.         -0.11740979  0.
  0.         -0.         -0.          0.14261469  0.         -0.
 -0.          0.         -0.59548354 -0.        ]

In [251]:
#idx = 9186
lasso_classifier = Lasso(alpha=0.1)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
print(lasso_classifier.coef_)
#print(lasso_classifier.intercept_)

[-0.          0.         -0.         -0.         -0.04059238  0.
  0.         -0.         -0.          0.07508865  0.         -0.
 -0.          0.06717732 -0.67675436 -0.        ]

In [259]:
#idx = 2762998
lasso_classifier = Lasso(alpha=0.1)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
print(lasso_classifier.coef_)
#print(lasso_classifier.intercept_)

[-0.          0.          0.          0.4288372  -0.21016456 -0.
  0.         -0.         -0.          0.          0.07228045 -0.
 -0.          0.         -0.7131233   0.        ]

In [218]:
# idx = 8891
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[14  9  4 13 12 11 10 15  8  7]
z_14: -0.5954835414886475
z_9: 0.1426146924495697
z_4: -0.11740978807210922
z_13: 0.0
z_12: -0.0
z_11: -0.0
z_10: 0.0
z_15: -0.0
z_8: -0.0
z_7: -0.0

In [252]:
#idx = 9186
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[14  9 13  4 12 11 10 15  8  7]
z_14: -0.676754355430603
z_9: 0.07508864998817444
z_13: 0.06717731803655624
z_4: -0.04059237986803055
z_12: -0.0
z_11: -0.0
z_10: 0.0
z_15: -0.0
z_8: -0.0
z_7: -0.0

In [261]:
#idx = 2762998
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[14  3  4 10 12 11 13 15  8  9]
z_14: -0.7131233215332031
z_3: 0.42883720993995667
z_4: -0.21016456186771393
z_10: 0.07228045165538788
z_12: -0.0
z_11: -0.0
z_13: 0.0
z_15: 0.0
z_8: -0.0
z_9: 0.0

In [217]:
y_pred = lasso_classifier.predict(test_transaction_latent)
print(y_pred)
print('R squared training set', lasso_classifier.score(lasso_x_train, lasso_y_train))

[1.8182106]
R squared training set 0.9356386065483093

## 3.3. Security bought or sold at an unusual time:
It is unusual for clients to trade specific securities outside of a specific timeframe (for example, outside of the opening and closing times of a stock exchange).

In [295]:
anomaly_type = 3
#idx = 1260		
#idx = 1157
idx = 2191296
z_train_a = z_train[y_pred_train == anomaly_type]
y_train_a = y_pred_train[y_pred_train == anomaly_type]
print(z_train_a.shape)
print(y_train_a.shape)

(11425, 16)
(11425,)

In [296]:
x = torch.tensor(X_test[idx], dtype=torch.float32).reshape(1, -1)
#x = X_test[idx].reshape(1, -1)

print(x.shape)
print(x[:, :6])
print(y_test[idx])
print(y_pred_test[idx])

model.encoder.eval()
test_transaction_latent = model.encoder(x)
test_transaction_latent = test_transaction_latent.cpu().detach().numpy()
test_transaction_latent = test_transaction_latent.reshape(1, -1)
test_transaction_latent.shape

torch.Size([1, 121])
tensor([[0.4377, 0.0000, 1.0000, 1.0000, 0.0000, 0.0000]])
3
3

(1, 16)

In [297]:
df_correct_preds.filter(pl.col("index") == idx)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 219 ┆ 3   ┆ 295 ┆ 201 ┆ Cli ┆ 3   ┆ 1   ┆ 0.4 ┆ 0   ┆ 1   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 1   ┆ 25  ┆ 4   ┆ 55  ┆ fal ┆ 2.7 ┆ 1.9 ┆ 1.6 ┆ 1.4 ┆ 1.3 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.7 ┆ 1.3 ┆ 1.4 ┆ 0.2 ┆ -1. ┆ 2.9 ┆ 0.8 ┆ 1.1 ┆ 4.9 ┆ 7.0 ┆ 8.2 ┆ -0. ┆ -6. ┆ -5. ┆ -7. ┆ -0. ┆ 3.2 ┆ 5.2 ┆ 5.5 ┆ -0. ┆ -5. ┆ -3. ┆ -4. ┆ 2.2 ┆ 4.2 ┆ 0.6 ┆ 1.2 ┆ 1.3 ┆ -6. ┆ -5. ┆ -7. ┆ -0. ┆ -1. ┆ -4. ┆ -5. ┆ -1. ┆ -3. ┆ -9. ┆ -12 ┆ -0. ┆ -2. ┆ -9. ┆ -11 ┆ -0. ┆ 9.4 ┆ 13. ┆ 13. ┆ 1.4 ┆ -1. ┆ -2. ┆ -3. ┆ -0. ┆ -1. ┆ -1. ┆ -2. ┆ -0. ┆ 0.3 ┆ 0.4 ┆ 0.8 ┆ 0.3 ┆ -0. ┆ 5.9 ┆ 0.8 ┆ 2.1 ┆ 0.2 ┆ -1. │
│ 129 ┆     ┆ 823 ┆ 9-0 ┆ ent ┆     ┆     ┆ 376 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 207 ┆ 587 ┆ 213 ┆ 438 ┆ 393 ┆ 669 ┆ 284 ┆ 112 ┆     ┆     ┆ 390 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 433 ┆ 183 ┆ 071 ┆     ┆     ┆ 141 ┆ 000 ┆ 000 ┆ 000 ┆ 170 ┆ 654 ┆ 935 ┆ 762 ┆ 016 ┆ 910 ┆ 313 ┆ 438 ┆ 937 ┆ 376 ┆ 814 ┆ 384 ┆ 234 ┆ 238 ┆ 187 ┆ 101 ┆ 889 ┆ 699 ┆ 940 ┆ 229 ┆ 706 ┆ 658 ┆ 395 ┆ 271 ┆ 805 ┆ 538 ┆ 143 ┆ 870 ┆ 749 ┆ 476 ┆ 476 ┆ 095 ┆ 535 ┆ 684 ┆ 980 ┆ 687 ┆ 160 ┆ 802 ┆ .09 ┆ 701 ┆ 932 ┆ 215 ┆ .54 ┆ 921 ┆ 106 ┆ 134 ┆ 971 ┆ 246 ┆ 928 ┆ 902 ┆ 583 ┆ 769 ┆ 664 ┆ 882 ┆ 476 ┆ 636 ┆ 422 ┆ 566 ┆ 273 ┆ 475 ┆ 255 ┆ 349 ┆ 720 ┆ 953 ┆ 512 ┆ 599 │
│ 6   ┆     ┆ 20  ┆ 3-2 ┆ _06 ┆     ┆     ┆ 87  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 86  ┆ 62  ┆ 36  ┆ 76  ┆ 78  ┆ 069 ┆ 955 ┆ 912 ┆     ┆     ┆ 533 ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 523 ┆ 119 ┆ 133 ┆     ┆     ┆ 91  ┆ 208 ┆ 167 ┆ 56  ┆ 8   ┆ 56  ┆ 61  ┆ 27  ┆ 961 ┆ 05  ┆ 14  ┆ 92  ┆     ┆ 61  ┆ 72  ┆ 886 ┆ 29  ┆ 993 ┆ 119 ┆ 634 ┆ 03  ┆ 15  ┆ 68  ┆ 192 ┆ 367 ┆ 61  ┆ 354 ┆ 92  ┆ 02  ┆ 34  ┆ 33  ┆ 32  ┆ 081 ┆ 462 ┆ 17  ┆ 479 ┆ 993 ┆ 434 ┆ 527 ┆ 743 ┆ 481 ┆ 353 ┆ 300 ┆ 652 ┆ 617 ┆ 009 ┆ 153 ┆ 833 ┆ 14  ┆ 068 ┆ 06  ┆ 29  ┆ 348 ┆ 491 ┆ 18  ┆ 643 ┆ 932 ┆ 942 ┆ 037 ┆ 684 ┆ 7   ┆ 13  ┆ 69  ┆ 66  ┆ 07  ┆ 58  ┆ 9   ┆ 67  ┆ 12  ┆ 508 │
│     ┆     ┆     ┆ 5   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 55: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 24  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [298]:
knn_normal = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_normal.fit(z_train_n)
distances_n, indices_n = knn_normal.kneighbors(test_transaction_latent, n_neighbors=k)
print(indices_n)
print(distances_n)

knn_anomaly = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_anomaly.fit(z_train_a)
distances_a, indices_a = knn_anomaly.kneighbors(test_transaction_latent, n_neighbors=k)
print(indices_a)
print(distances_a)

[[19181254  4550302 19181207  4550311  4550573 19181273  4551119  4549768
  19181228]]
[[2.00121045 2.05460787 2.06765532 2.07407093 2.07464314 2.09097219
  2.09130216 2.11779213 2.12236404]]
[[ 5888  4770  5929  5902  5856  5883  5868 10495  4838]]
[[1.13939023 1.14369786 1.3032707  1.35032642 1.36107588 1.36896372
  1.40083265 1.40411448 1.41559124]]

In [299]:
lasso_x_train = np.vstack((z_train_n[indices_n.flatten().tolist()], z_train_a[indices_a.flatten().tolist()]))
lasso_y_train = np.concatenate((y_train_n[indices_n.flatten().tolist()], y_train_a[indices_a.flatten().tolist()]))

print(lasso_x_train.shape)
print(lasso_y_train.shape)

(18, 16)
(18,)

In [300]:
lasso_classifier = Lasso(alpha=0.1)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
print(lasso_classifier.coef_)
#print(lasso_classifier.intercept_)

[ 0.         -0.          0.         -0.         -0.          0.
 -0.00651955 -0.          0.          0.          2.3100157   0.
 -0.          0.         -0.6542186   0.        ]

In [270]:
# idx = 1260
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[15  9 14 13 12 11 10  8  7  6]
z_15: 1.6302036046981812
z_9: 1.4055988788604736
z_14: -0.5636571645736694
z_13: 0.0
z_12: 0.0
z_11: 0.0
z_10: 0.0
z_8: -0.0
z_7: -0.0
z_6: -0.0

In [278]:
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[15  4  3  8 12 11 13 14  9 10]
z_15: 1.805695652961731
z_4: -1.358310580253601
z_3: 1.0342575311660767
z_8: 0.10734690725803375
z_12: -0.0
z_11: 0.0
z_13: 0.0
z_14: -0.0
z_9: 0.0
z_10: 0.0

In [301]:
#idx= 2191296
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[10 14  6 13 12 11  9 15  8  7]
z_10: 2.3100156784057617
z_14: -0.6542186141014099
z_6: -0.006519550457596779
z_13: 0.0
z_12: -0.0
z_11: 0.0
z_9: 0.0
z_15: 0.0
z_8: 0.0
z_7: -0.0

## 2.4. Large asset withdrawal:
A sudden spike in transaction amount withdrawn from an account or transferred out, which deviates from the previous transactional activity and is absent of any commercial rationale or related corporate action event.

In [333]:
anomaly_type = 4
#idx = 16483
#idx = 43121
idx = 1578200
z_train_a = z_train[y_pred_train == anomaly_type]
y_train_a = y_pred_train[y_pred_train == anomaly_type]
print(z_train_a.shape)
print(y_train_a.shape)

(60973, 16)
(60973,)

In [334]:
x = torch.tensor(X_test[idx], dtype=torch.float32).reshape(1, -1)
#x = X_test[idx].reshape(1, -1)

print(x.shape)
print(x[:, :6])
print(y_test[idx])
print(y_pred_test[idx])

model.encoder.eval()
test_transaction_latent = model.encoder(x)
test_transaction_latent = test_transaction_latent.cpu().detach().numpy()
test_transaction_latent = test_transaction_latent.reshape(1, -1)
test_transaction_latent.shape

torch.Size([1, 121])
tensor([[0.2837, 0.0000, 1.0000, 0.0000, 1.0000, 0.0000]])
4
4

(1, 16)

In [335]:
df_correct_preds.filter(pl.col("index") == idx)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 157 ┆ 4   ┆ 283 ┆ 201 ┆ Cli ┆ 4   ┆ 1   ┆ 0.2 ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 4   ┆ 21  ┆ 13  ┆ 52  ┆ fal ┆ 1.8 ┆ 1.3 ┆ 1.0 ┆ 0.9 ┆ 0.9 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 0.4 ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -1. ┆ 1.2 ┆ -0. ┆ -0. ┆ -1. ┆ 1.1 ┆ 0.8 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.1 ┆ 0.3 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.1 ┆ -0. ┆ -0. ┆ 2.2 ┆ 0.6 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.1 ┆ 0.3 ┆ -0. ┆ -0. ┆ 0.1 ┆ -0. ┆ -0. ┆ -0. ┆ 0.1 ┆ -0. ┆ -0. ┆ -0. ┆ 0.3 ┆ 0.1 ┆ -0. ┆ 0.3 ┆ -0. ┆ -0. ┆ 0.7 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.3 ┆ -0. ┆ 0.0 ┆ 2.6 ┆ -0. ┆ 1.1 ┆ -0. ┆ 0.6 │
│ 820 ┆     ┆ 890 ┆ 9-0 ┆ ent ┆     ┆     ┆ 837 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 689 ┆ 240 ┆ 999 ┆ 915 ┆ 329 ┆ 669 ┆ 284 ┆ 112 ┆     ┆     ┆ 390 ┆ 917 ┆ 698 ┆ 576 ┆ 484 ┆ 433 ┆ 183 ┆ 071 ┆     ┆     ┆ 565 ┆ 000 ┆ 000 ┆ 000 ┆ 131 ┆ 087 ┆ 123 ┆ 803 ┆ 068 ┆ 161 ┆ 441 ┆ 310 ┆ 071 ┆ 968 ┆ 420 ┆ 360 ┆ 335 ┆ 215 ┆ 093 ┆ 043 ┆ 040 ┆ 598 ┆ 203 ┆ 158 ┆ 356 ┆ 016 ┆ 508 ┆ 271 ┆ 128 ┆ 167 ┆ 145 ┆ 372 ┆ 397 ┆ 502 ┆ 236 ┆ 037 ┆ 941 ┆ 400 ┆ 296 ┆ 387 ┆ 831 ┆ 607 ┆ 095 ┆ 100 ┆ 809 ┆ 649 ┆ 921 ┆ 538 ┆ 516 ┆ 386 ┆ 154 ┆ 429 ┆ 863 ┆ 425 ┆ 569 ┆ 909 ┆ 574 ┆ 509 ┆ 547 ┆ 888 ┆ 053 ┆ 139 ┆ 596 ┆ 161 ┆ 431 ┆ 711 ┆ 306 ┆ 998 ┆ 500 ┆ 304 │
│ 0   ┆     ┆ 41  ┆ 3-2 ┆ _12 ┆     ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 77  ┆ 96  ┆ 86  ┆ 82  ┆ 8   ┆ 069 ┆ 955 ┆ 912 ┆     ┆     ┆ 533 ┆ 766 ┆ 787 ┆ 665 ┆ 611 ┆ 523 ┆ 119 ┆ 133 ┆     ┆     ┆ 82  ┆ 208 ┆ 167 ┆ 56  ┆ 3   ┆ 529 ┆ 89  ┆ 66  ┆ 142 ┆ 48  ┆ 88  ┆ 28  ┆ 814 ┆ 032 ┆ 084 ┆ 45  ┆ 74  ┆ 85  ┆ 69  ┆ 862 ┆ 74  ┆ 899 ┆ 583 ┆ 338 ┆ 57  ┆ 457 ┆ 863 ┆ 92  ┆ 53  ┆ 957 ┆ 61  ┆ 707 ┆ 26  ┆ 38  ┆ 11  ┆ 927 ┆ 021 ┆ 9   ┆ 796 ┆ 288 ┆ 17  ┆ 68  ┆ 626 ┆ 306 ┆ 296 ┆ 83  ┆ 27  ┆ 934 ┆ 98  ┆ 228 ┆ 444 ┆ 84  ┆ 871 ┆ 828 ┆ 989 ┆ 407 ┆ 383 ┆ 322 ┆ 755 ┆ 144 ┆ 912 ┆ 232 ┆ 88  ┆ 868 ┆ 99  ┆ 61  ┆ 357 ┆ 52  ┆ 194 ┆ 34  │
│     ┆     ┆     ┆ 1   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 13: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 52: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 58  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [336]:
knn_normal = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_normal.fit(z_train_n)
distances_n, indices_n = knn_normal.kneighbors(test_transaction_latent, n_neighbors=k)
print(indices_n)
print(distances_n)

knn_anomaly = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_anomaly.fit(z_train_a)
distances_a, indices_a = knn_anomaly.kneighbors(test_transaction_latent, n_neighbors=k)
print(indices_a)
print(distances_a)

[[22637796  6515247 14918450 21045242 23973410 18005843 18596616 17494687
  24128359]]
[[2.09333301 2.20503902 2.21301699 2.23646998 2.27940512 2.28431606
  2.3295927  2.33245277 2.35924649]]
[[51779 51782 51854 51914 51770 51685 51789 51686 56578]]
[[0.6487757  0.66346639 0.7476024  0.81965625 0.82133055 0.83718187
  0.86397141 0.86418015 0.87199795]]

In [337]:
lasso_x_train = np.vstack((z_train_n[indices_n.flatten().tolist()], z_train_a[indices_a.flatten().tolist()]))
lasso_y_train = np.concatenate((y_train_n[indices_n.flatten().tolist()], y_train_a[indices_a.flatten().tolist()]))

print(lasso_x_train.shape)
print(lasso_y_train.shape)

(18, 16)
(18,)

In [338]:
lasso_classifier = Lasso(alpha=0.1)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
print(lasso_classifier.coef_)
#print(lasso_classifier.intercept_)

[-0.         -0.         -0.          0.68520284 -1.7985528   0.
 -0.         -0.         -0.          0.          0.         -0.51679516
  0.         -0.9433232  -0.         -0.39799213]

In [313]:
# idx = 16483
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[14  2 11 15 12 10  9 13  8  7]
z_14: -0.8668021559715271
z_2: -0.6827273368835449
z_11: -0.5504565238952637
z_15: -0.12361042946577072
z_12: 0.0
z_10: 0.0
z_9: 0.0
z_13: -0.0
z_8: 0.0
z_7: -0.0

In [330]:
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[11 15 13  3 14  0 12 10  8  9]
z_11: -1.0144938230514526
z_15: -0.3820912539958954
z_13: -0.20467519760131836
z_3: 0.18361549079418182
z_14: -0.13533329963684082
z_0: -0.08610198646783829
z_12: 0.0
z_10: 0.0
z_8: 0.0
z_9: -0.0

In [339]:
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[ 4 13  3 11 15 10 12 14  8  9]
z_4: -1.7985527515411377
z_13: -0.9433231949806213
z_3: 0.6852028369903564
z_11: -0.5167951583862305
z_15: -0.3979921340942383
z_10: 0.0
z_12: 0.0
z_14: -0.0
z_8: -0.0
z_9: 0.0

In [340]:
y_pred = lasso_classifier.predict(test_transaction_latent)
print(y_pred)
print('R squared training set', lasso_classifier.score(lasso_x_train, lasso_y_train))

[3.3733356]
R squared training set 0.9586156010627747

## 3.5. An unusually large amount of collateral transferred in and out of an account within a short period of time:
This behavior is unusual as a client would not be able to invest by simply trading collateral, or at least such a strategy would be unusual.

In [361]:
# idx = 37661
# idx = 2762376
idx = 2742220
anomaly_type = 5
z_train_a = z_train[y_pred_train == anomaly_type]
y_train_a = y_pred_train[y_pred_train == anomaly_type]
print(z_train_a.shape)
print(y_train_a.shape)

(68173, 16)
(68173,)

In [362]:
x = torch.tensor(X_test[idx], dtype=torch.float32).reshape(1, -1)
#x = X_test[idx].reshape(1, -1)

print(x.shape)
print(x[:, :6])
print(y_test[idx])
print(y_pred_test[idx])

model.encoder.eval()
test_transaction_latent = model.encoder(x)
test_transaction_latent = test_transaction_latent.cpu().detach().numpy()
test_transaction_latent = test_transaction_latent.reshape(1, -1)
test_transaction_latent.shape

torch.Size([1, 121])
tensor([[0.1276, 1.0000, 0.0000, 1.0000, 0.0000, 0.0000]])
5
5

(1, 16)

In [363]:
df_correct_preds.filter(pl.col("index") == idx)

shape: (1, 132)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ ind ┆ Mod ┆ id  ┆ dat ┆ Ori ┆ Ano ┆ Ano ┆ amo ┆ Inp ┆ Inp ┆ Mar ┆ Mar ┆ Mar ┆ Mar ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Pro ┆ Cur ┆ Cur ┆ day ┆ day ┆ hou ┆ min ┆ is_ ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ mar ┆ mar ┆ mar ┆ mar ┆ mar ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ pro ┆ ori ┆ mar ┆ pro ┆ pro ┆ day ┆ day ┆ day ┆ day ┆ hou ┆ hou ┆ min ┆ min ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ rol ┆ cum ┆ cum ┆ cum ┆ cum ┆ cum ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur │
│ ex  ┆ el  ┆ --- ┆ eti ┆ gin ┆ mal ┆ mal ┆ unt ┆ utO ┆ utO ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ ren ┆ ren ┆ _of ┆ _of ┆ r   ┆ ute ┆ rou ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ ket ┆ ket ┆ ket ┆ ket ┆ ket ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ duc ┆ gin ┆ ket ┆ duc ┆ duc ┆ _of ┆ _of ┆ _of ┆ _of ┆ r_s ┆ r_c ┆ ute ┆ ute ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ lin ┆ cou ┆ cou ┆ cou ┆ cou ┆ cou ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren │
│ --- ┆ Pre ┆ u32 ┆ me  ┆ ato ┆ y   ┆ y_b ┆ _lo ┆ utp ┆ utp ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ t   ┆ cy_ ┆ cy_ ┆ _we ┆ _mo ┆ --- ┆ --- ┆ nde ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_t ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ t_c ┆ ato ┆ _in ┆ t_t ┆ t_c ┆ _we ┆ _we ┆ _mo ┆ _mo ┆ in  ┆ os  ┆ _si ┆ _co ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_m ┆ g_s ┆ g_s ┆ g_s ┆ g_s ┆ g_n ┆ g_n ┆ g_n ┆ g_n ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ nt_ ┆ utp ┆ _fr ┆ t   ┆ t   ┆ cy_ │
│ u32 ┆ dic ┆     ┆ --- ┆ r   ┆ --- ┆ in  ┆ g   ┆ ut_ ┆ ut_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Typ ┆ Cla ┆ Cla ┆ Cla ┆ Cla ┆ 1   ┆ 2   ┆ ek  ┆ nth ┆ i8  ┆ i8  ┆ d   ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ r_i ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ ype ┆ ype ┆ ype ┆ ype ┆ ype ┆ las ┆ las ┆ las ┆ las ┆ las ┆ r_i ┆ dex ┆ ype ┆ las ┆ ek_ ┆ ek_ ┆ nth ┆ nth ┆ --- ┆ --- ┆ n   ┆ s   ┆ ean ┆ ean ┆ ean ┆ ean ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ ean ┆ ean ┆ ean ┆ ean ┆ td_ ┆ td_ ┆ td_ ┆ td_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ ax_ ┆ in_ ┆ in_ ┆ in_ ┆ in_ ┆ um_ ┆ um_ ┆ um_ ┆ um_ ┆ _tr ┆ _tr ┆ _tr ┆ _tr ┆ Inp ┆ Mar ┆ Pro ┆ Pro ┆ Cur ┆ ut_ ┆ eq_ ┆ Typ ┆ Cla ┆ fre │
│     ┆ tio ┆     ┆ dat ┆ --- ┆ i64 ┆ --- ┆ --- ┆ Buy ┆ Sel ┆ u8  ┆ u8  ┆ u8  ┆ u8  ┆ e_A ┆ e_B ┆ e_C ┆ e_E ┆ e_E ┆ e_E ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_F ┆ e_R ┆ e_S ┆ ss_ ┆ ss_ ┆ ss_ ┆ ss_ ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _in ┆ _in ┆ _in ┆ _in ┆ _in ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ s_i ┆ nde ┆ _am ┆ _in ┆ s_i ┆ sin ┆ cos ┆ _si ┆ _co ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ _1h ┆ _12 ┆ _24 ┆ _7d ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ ans ┆ ans ┆ ans ┆ ans ┆ _or ┆ _or ┆ _or ┆ _or ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ori ┆ ans ┆ ans ┆ ans ┆ ans ┆ utO ┆ ket ┆ duc ┆ duc ┆ ren ┆ fre ┆ ori ┆ e_f ┆ ss_ ┆ q_o │
│     ┆ n   ┆     ┆ eti ┆ str ┆     ┆ i8  ┆ f64 ┆ --- ┆ l   ┆     ┆     ┆     ┆     ┆ DR  ┆ ond ┆ AAD ┆ TOE ┆ TOE ┆ qui ┆ X   ┆ XFo ┆ XSw ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ utu ┆ epo ┆ imp ┆ ADR ┆ Cas ┆ Ext ┆ Tra ┆ u8  ┆ u8  ┆ i8  ┆ i8  ┆     ┆     ┆ boo ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ dex ┆ dex ┆ dex ┆ dex ┆ dex ┆ nde ┆ nde ┆ nde ┆ nde ┆ nde ┆ x_a ┆ oun ┆ dex ┆ nde ┆ --- ┆ --- ┆ n   ┆ s   ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆ h   ┆ h   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ act ┆ act ┆ act ┆ act ┆ igi ┆ igi ┆ igi ┆ igi ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ gin ┆ act ┆ act ┆ act ┆ act ┆ utp ┆ --- ┆ t   ┆ t   ┆ cy  ┆ q_o ┆ gin ┆ req ┆ fre ┆ rig │
│     ┆ --- ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ R   ┆ qui ┆ qui ┆ ty  ┆ --- ┆ rwa ┆ ap  ┆ reB ┆ reC ┆ reE ┆ reE ┆ reF ┆ reO ┆ --- ┆ leT ┆ Con ┆ h   ┆ ern ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ _ti ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ x_t ┆ mou ┆ t_d ┆ _am ┆ x_a ┆ f64 ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ ion ┆ ion ┆ ion ┆ ion ┆ nat ┆ nat ┆ nat ┆ nat ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ato ┆ ion ┆ ion ┆ ion ┆ ion ┆ ut  ┆ f64 ┆ Typ ┆ Cla ┆ --- ┆ rig ┆ ato ┆ _or ┆ q_o ┆ ina │
│     ┆ i64 ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆ u8  ┆ u8  ┆ --- ┆ ty  ┆ tyI ┆ --- ┆ u8  ┆ rd  ┆ --- ┆ ond ┆ omm ┆ qui ┆ qui ┆ X   ┆ pti ┆ u8  ┆ ran ┆ ver ┆ in  ┆ al  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mes ┆ mes ┆ mes ┆ mes ┆ mes ┆ ime ┆ ime ┆ ime ┆ ime ┆ ime ┆ nt_ ┆ iff ┆ oun ┆ mou ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s_1 ┆ s_1 ┆ s_2 ┆ s_7 ┆ or_ ┆ or_ ┆ or_ ┆ or_ ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ r_1 ┆ r_1 ┆ r_2 ┆ r_7 ┆ s_o ┆ s_o ┆ s_o ┆ s_o ┆ --- ┆     ┆ e   ┆ ss  ┆ f64 ┆ ina ┆ r   ┆ igi ┆ rig ┆ tor │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ --- ┆ nde ┆ u8  ┆     ┆ --- ┆ u8  ┆ --- ┆ odi ┆ ty  ┆ tyI ┆ --- ┆ onE ┆     ┆ sfe ┆ sio ┆ /   ┆ fee ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ iff ┆ iff ┆ iff ┆ iff ┆ iff ┆ tam ┆ tam ┆ tam ┆ tam ┆ tam ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ dif ┆ _1  ┆ t_d ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ 1h  ┆ 12h ┆ 24h ┆ 7d  ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ h   ┆ 2h  ┆ 4h  ┆ d   ┆ rig ┆ rig ┆ rig ┆ rig ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆ tor ┆ --- ┆ nat ┆ ina ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆ x   ┆     ┆     ┆ u8  ┆     ┆ u8  ┆ ty  ┆ --- ┆ nde ┆ u8  ┆ qui ┆     ┆ r   ┆ n   ┆ out ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dif ┆ dif ┆ dif ┆ dif ┆ dif ┆ _1  ┆ _2  ┆ _3  ┆ _4  ┆ _5  ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ p_d ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ mp_ ┆ f_1 ┆ --- ┆ iff ┆ dif ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ina ┆ ina ┆ ina ┆ ina ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ or  ┆ tor ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u8  ┆ x   ┆     ┆ t…  ┆     ┆ --- ┆ --- ┆ (w… ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ --- ┆ f64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ …   ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ --- ┆     ┆ --- ┆     ┆ u8  ┆ u8  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u8  ┆     ┆ u8  ┆     ┆     ┆     ┆ u8  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 274 ┆ 5   ┆ 293 ┆ 201 ┆ Cli ┆ 5   ┆ 1   ┆ 0.1 ┆ 1   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 1   ┆ 0   ┆ 1   ┆ 25  ┆ 20  ┆ 19  ┆ fal ┆ 2.7 ┆ 1.9 ┆ 1.6 ┆ 1.4 ┆ 1.3 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.3 ┆ -0. ┆ -0. ┆ -0. ┆ 2.4 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ -1. ┆ -2. ┆ 0.7 ┆ 1.3 ┆ 1.4 ┆ 0.2 ┆ 1.2 ┆ 1.9 ┆ -1. ┆ -0. ┆ -1. ┆ -0. ┆ -0. ┆ -0. ┆ 0.2 ┆ 1.1 ┆ 0.4 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.3 ┆ -0. ┆ -0. ┆ 0.5 ┆ 0.5 ┆ 1.0 ┆ 1.3 ┆ 0.3 ┆ 1.2 ┆ 0.5 ┆ 0.0 ┆ 0.2 ┆ 0.0 ┆ -0. ┆ -1. ┆ 0.3 ┆ 0.1 ┆ -0. ┆ -0. ┆ 0.4 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.1 ┆ 0.3 ┆ 1.4 ┆ 0.2 ┆ 0.1 ┆ -0. ┆ -0. ┆ 0.1 ┆ 0.1 ┆ -0. ┆ -0. ┆ -0. ┆ 0.4 ┆ 0.2 ┆ 0.3 ┆ 0.3 ┆ -6. ┆ 0.8 ┆ -0. ┆ 0.2 ┆ 0.6 │
│ 222 ┆     ┆ 151 ┆ 9-0 ┆ ent ┆     ┆     ┆ 275 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ 229 ┆ 603 ┆ 226 ┆ 450 ┆ 404 ┆ 669 ┆ 284 ┆ 112 ┆     ┆     ┆ 416 ┆ 711 ┆ 698 ┆ 576 ┆ 484 ┆ 207 ┆ 183 ┆ 071 ┆     ┆     ┆ 984 ┆ 000 ┆ 487 ┆ 445 ┆ 170 ┆ 654 ┆ 935 ┆ 762 ┆ 279 ┆ 005 ┆ 344 ┆ 437 ┆ 523 ┆ 726 ┆ 866 ┆ 731 ┆ 098 ┆ 775 ┆ 906 ┆ 105 ┆ 947 ┆ 587 ┆ 661 ┆ 519 ┆ 077 ┆ 986 ┆ 065 ┆ 728 ┆ 213 ┆ 412 ┆ 941 ┆ 870 ┆ 352 ┆ 064 ┆ 189 ┆ 229 ┆ 832 ┆ 469 ┆ 163 ┆ 426 ┆ 882 ┆ 149 ┆ 019 ┆ 678 ┆ 741 ┆ 941 ┆ 139 ┆ 921 ┆ 114 ┆ 217 ┆ 762 ┆ 246 ┆ 761 ┆ 118 ┆ 330 ┆ 712 ┆ 790 ┆ 071 ┆ 320 ┆ 600 ┆ 024 ┆ 670 ┆ 052 ┆ 561 ┆ 512 ┆ 545 ┆ 722 ┆ 270 ┆ 475 ┆ 204 │
│ 0   ┆     ┆ 63  ┆ 3-2 ┆ _06 ┆     ┆     ┆ 58  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 51  ┆ 9   ┆ 62  ┆ 3   ┆ 15  ┆ 069 ┆ 955 ┆ 912 ┆     ┆     ┆ 46  ┆ 74  ┆ 787 ┆ 665 ┆ 611 ┆ 02  ┆ 119 ┆ 133 ┆     ┆     ┆ 276 ┆ 208 ┆ 097 ┆ 17  ┆ 8   ┆ 56  ┆ 61  ┆ 27  ┆ 68  ┆ 58  ┆ 977 ┆ 218 ┆ 585 ┆ 696 ┆ 729 ┆ 116 ┆ 02  ┆ 84  ┆ 27  ┆ 75  ┆ 899 ┆ 114 ┆ 039 ┆ 632 ┆ 862 ┆ 77  ┆ 88  ┆ 241 ┆ 48  ┆ 03  ┆     ┆ 32  ┆ 52  ┆ 1   ┆ 74  ┆ 42  ┆ 68  ┆ 53  ┆ 438 ┆ 016 ┆ 66  ┆ 56  ┆ 064 ┆ 652 ┆ 39  ┆ 48  ┆ 594 ┆ 833 ┆ 053 ┆ 36  ┆ 58  ┆ 29  ┆ 73  ┆ 55  ┆ 82  ┆ 058 ┆ 22  ┆ 07  ┆ 819 ┆ 53  ┆ 059 ┆ 78  ┆ 99  ┆ 82  ┆ 18  ┆ 54  ┆ 19  ┆ 368 ┆     ┆ 01  │
│     ┆     ┆     ┆ 5   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 20: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 19: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ 22  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [364]:
knn_normal = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_normal.fit(z_train_n)
distances_n, indices_n = knn_normal.kneighbors(test_transaction_latent, n_neighbors=k)
print(indices_n)
print(distances_n)

knn_anomaly = NearestNeighbors(n_neighbors=k, algorithm='auto', metric='euclidean')
knn_anomaly.fit(z_train_a)
distances_a, indices_a = knn_anomaly.kneighbors(test_transaction_latent, n_neighbors=k)
print(indices_a)
print(distances_a)

[[2224812 2445974 2486129 2863133 2452079 3157412 2840016 1799853  537756]]
[[3.30597401 3.36121106 3.45149326 3.50405145 3.50886726 3.53707814
  3.54500651 3.54833174 3.55391145]]
[[36947 64918 64916 64913 32603 29873 19184 32601 64888]]
[[0.73515326 0.8501938  0.88848692 0.93049419 0.94628245 0.96698058
  0.97500175 0.97839004 1.01206148]]

In [365]:
lasso_x_train = np.vstack((z_train_n[indices_n.flatten().tolist()], z_train_a[indices_a.flatten().tolist()]))
lasso_y_train = np.concatenate((y_train_n[indices_n.flatten().tolist()], y_train_a[indices_a.flatten().tolist()]))

print(lasso_x_train.shape)
print(lasso_y_train.shape)

(18, 16)
(18,)

In [366]:
lasso_classifier = Lasso(alpha=0.1)
lasso_classifier.fit(lasso_x_train, lasso_y_train)
print(lasso_classifier.coef_)
#print(lasso_classifier.intercept_)

[ 0.          0.81061304 -0.          0.         -0.          0.
 -0.1136227  -0.         -0.9288145   0.          0.         -0.83087265
  1.3570399  -0.         -0.38097972 -0.        ]

In [348]:
# idx = 16483
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[ 4  7 13  8 10  0 11  1 15  9]
z_4: -2.842630624771118
z_7: -1.797913908958435
z_13: -1.7776914834976196
z_8: -0.8401194214820862
z_10: 0.7909547090530396
z_0: -0.6901487708091736
z_11: -0.5478876233100891
z_1: 0.5196952819824219
z_15: -0.3222387135028839
z_9: -0.0

In [356]:
#idx = 2762376
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[ 6  4  8  1 12 14 13 15  9 10]
z_6: -1.2893599271774292
z_4: -1.1086502075195312
z_8: -1.0477161407470703
z_1: 0.3213449716567993
z_12: 0.31699803471565247
z_14: -0.08331853151321411
z_13: -0.0
z_15: -0.0
z_9: 0.0
z_10: 0.0

In [367]:
#idx = 2742220
sorted_importance = show_importance_latent(lasso_classifier.coef_, n_features=10)

[12  8 11  1 14  6 13 15  9 10]
z_12: 1.3570399284362793
z_8: -0.9288144707679749
z_11: -0.830872654914856
z_1: 0.8106130361557007
z_14: -0.3809797167778015
z_6: -0.11362269520759583
z_13: -0.0
z_15: -0.0
z_9: 0.0
z_10: 0.0